#!/bin/sh 
#
# Check the installation for missing applications
#

DDS_DIST=${DDS_DIST:-/tstapps/global}

appdir=$DDS_DIST/`$DDSROOT/src/lib/host/HostDir  -x`
libdir=$DDSROOT/lib/`$DDSROOT/src/lib/host/HostDir  -b`/`$DDSROOT/src/lib/host/HostComp -d`

n=0
m=0
N=0
M=0

cd $DDSROOT/src/cmd
progs=`ls */Makefile`
for prog in $progs; do
   app=${prog%/Makefile}
   lib=`echo $app|sed 's/^lib.*/lib/'`
   if [ "$lib" = lib ]; then
      m=$(($m+1))
      if [ ! -f $libdir/$app.a ]; then
         M=$(($M+1))
         echo "Application Library not installed: $libdir/$app.a"
         echo "(Go to $DDSROOT/src/cmd/$app and run 'make' & 'make install')"
      fi
   else 
      n=$(($n+1))
      if [ ! -f $appdir/$app ]; then
         N=$(($N+1))
         echo "Application Program not installed: $appdir/$app"
         echo "(Go to $DDSROOT/src/cmd/$app and run 'make' & 'make install')"
      fi
   fi
done

echo
if [ $M -gt 0 ]; then
   echo "*** $M Application Libraries not installed ***"
else
   echo "*** All $m Application Libraries installed ***"
fi
if [ $N -gt 0 ]; then
   echo "*** $N Application Programs not installed ***"
else
   echo "*** All $n Application Programs installed ***"
fi
