#!/bin/csh -f
#
# Script to cleanup application object files
#

#
# cleanup each applicaton
#
cd ${DDSROOT}/src/cmd
set progs = `ls */Makefile`

foreach prog ( $progs )
   set prog = ${prog:h}
   ( cd $prog;make clean )
end

