'\" t
.TH asciidump 1 "$Date: 2009-01-06 10:56:43 -0600 (Tue, 06 Jan 2009) $" "DDS Utility"
.ad b
.SH NAME
asciidump - Utility to dump binary data samples to an ascii file (DDS)
.SH SYNOPSIS
\fBasciidump <input> [<output>]
.SH DESCRIPTION
\fBasciidump\fR take an input file as specified by <input> and outputs
the data Samples into an ascii file as defined by <output> or piped out.
The output will consist of a column for each axis value followed by
the actual corresponding data sample value.
.SH AUTHOR
 Jerry Ehlers, \fBEPTG\fR
