'\" t
.TH dds_files 1 "$Date: 2007/01/15 19:38:26 $" "DDS Utility"
.ad b
.SH NAME
dds_files \ - Utility to processing history on files & formats (DDS).
.SH SYNOPSIS
\fBdds_ffiles [file1 [,file2...]] [-h]
.SH DESCRIPTION
\fBdds_files\fR returns the applications, datasets and formats from
the processing history in one or more DDS dictionaries.  The default
is to read dictionaries from stdin.
.SH AUTHOR
 Jerry Ehlers, \fBEPTG\fR
