#!/bin/sh
# RCS-t=DDS script, print history of axis description
#
# Maintained by Jerry Ehlers under DDS
#
if [ "$1" = -h -o "$1" = h -o "$1" = -help -o "$1" = help ]; then
   echo 'dds_axis:' history of axis description
   echo 'Example:' dds_axis '<' dictionary
   exit 1
fi

egrep '(cmd_title=|axis=|axis\.|size\.|label\.|origin\.|delta\.|units\.)' $1
status=$?
if [ "$status" != 0 ]; then 
   echo "No axes found!"
fi
