#!/bin/sh
# RCS-t=DDS script, print history of file names and formats

if [ "$1" = -h -o "$1" = h -o "$1" = -help -o "$1" = help ]; then
   echo 'dds_files:' history of file names and formats
   echo 'Example:' dds_files '<' dictionary
   exit 1
fi

egrep '(cmd_title=|(^|[ 	])in=|(^|[ 	])out=|data=|format=)' $1
status=$?
if [ "$status" != 0 ]; then
   echo "Nothing found!"
fi
