'\" t
.TH dds_mv 1 "$Date: 2008/11/05 15:32:25 $" "DDS Utility"
.ad b
.SH NAME
dds_mv \ - Utility to move dds datasets (DDS).
.SH SYNOPSIS
\fBdds_mv dict1 [dict2 [...dictn]] <directory>
.SH DESCRIPTION
\fBdds_mv\fR reads each of the listed DDS dictionaries and moves each of 
their binary files (as defined by each dictionary) to the specified directory.
Each dictionary will be modified to relfect the changed location of 
each corresponding binary file.
.SH AUTHOR
 Randy Selzler, \fBData-Warp\fR
 Jerry Ehlers, \fBEPTG\fR
