'\" t
.TH dds_rm 1 "$Date: 2006/02/13 23:30:05 $" "DDS Utility"
.ad b

.SH NAME
dds_rm \ - Utility to remove dds datasets (DDS).

.SH SYNOPSIS
\fBdds_rm dict1 [-o] [-t] [dict2 [...dictn]]

.SH DESCRIPTION
\fBdds_rm\fR removes each listed DDS dictionary along with their
corresponding binary file(s) (as defined by each dictionary).
If any data binary files are themselves dictionaries, then those
dictionaries are also scanned for their corresponding binaries.
However, if any of those binaries are actually a dictionary with
another corresponding binary, then it will terminate with an error
indicating the removal of those first.

.SH OPTIONS
.TP 5
\fB-o\fR
Specify this switch to also check that you are the owner before removing

.PP
.TP 5
\fB-t\fR
Specify this switch switch to only test what files would be removed 
without actually removing any.

.SH AUTHOR
 Randy Selzler, \fBData-Warp\fR
 Jerry Ehlers, \fBEPTG\fR
