#!/bin/sh
# RCS-t=DDS script, print history of where commands were applied
#
# Maintained by Jerry Ehlers under DDS
#

if [ "$1" = -h -o "$1" = h -o "$1" = -help -o "$1" = help ]; then
   echo 'dds_where:' history of where commands were applied
   echo 'Example:' dds_where '<' dictionary
   exit 1
fi

egrep '(cmd_title=|cmd_host=|cmd_cwd=)' $1
status=$?
if [ "$status" != 0 ]; then
   echo "Nothing found!"
fi
