'\" t
.TH dds_bu 1 "$Date: 2006/02/13 23:30:05 $" "DDS Utility"
.ad b
.SH NAME
dds_bu \ - Utility to backup a dds dataset to IDS (DDS).
.SH SYNOPSIS
\fBdds_bu <dict> <storage_set> <ids_machine> [<options>]
.SH DESCRIPTION
\fBdds_bu\fR takes a DDS dataset as specified by a dictionary (<dict>),
attaches the DDS binary to the dictionary and backs it up onto the IDS
system as specified by the IDS storage set (<storage_set>) and 
machine (<ids_machine>).  Extra optional definitions (eg. in_format=usp
out_format=fcube) can be specified at the end of the command line.
.SH AUTHOR
 Randy Selzler, \fBData-Warp\fR
 Jerry Ehlers, \fBEPTG\fR
