#!/bin/sh
# RCS-t=DDS script, print history of what commands were applied
#
# Maintained by Jerry Ehlers under DDS
#

if [ "$1" = -h -o "$1" = h -o "$1" = -help -o "$1" = help ]; then
   echo 'dds_what:' history of what commands were applied
   echo 'Example:' dds_what '<' dictionary
   exit 1
fi

egrep '(cmd_title=|cmd_name=)' $1
status=$?
if [ "$status" != 0 ]; then
   echo "No commands found!"
fi
