#!/bin/csh -f
#=======================================================
# backs up DDS file by attaching binary data to dictonary first
# --
# 10/24/97 wr
# 12/04/97 rma
# 04/02/99 jwe
#=======================================================
#

if ( $#argv < 3 || $#argv > 4 ) then
   echo " "
   echo "dds_bu - will attach the DDS binary file to the dictionalry file"
   echo "         and back it up onto the ids system"
   echo "Usage: dds_bu <dds_dictonary_file> <storage_set> <ids_machine> [options]"
   echo "Where: options = eg. in_format= usp out_format= fcube"
   echo " "
   exit 1
endif

#
# SET VARIABLES
#

set dict = $1
set IDS_SS = $2
set IDS_MACH = $3
set options = $4
set IDS_OUT = ${dict:gt}.ids.out

#
# ATTACH BINARY FILE AND WRITE TO TAPE
# (add "-x" to wait till finished - Feb 06)
#
dds_bridge in=${dict} out=stdout: out_data=dict: $options |\
ids_put -s ${IDS_MACH} -ss ${IDS_SS} -x -o ${dict} -lf $IDS_OUT
if ($status) then
   echo Error backing up ${dict}
   exit 1
endif

echo ${dict} backed up on ${IDS_MACH} in ${IDS_SS}

exit 0

