'\" t
.TH mbs-show 1 "$Date: 2009-01-06 10:56:43 -0600 (Tue, 06 Jan 2009) $" "DDS Utility"
.ad b
.SH NAME
mbs-show \ - Utility to list any old binaries available for a given program (DDS).
.SH SYNOPSIS
\fBmbs-show <program> 
.SH DESCRIPTION
\fBmbs-show\fR will list any old binaries available on the current architecture
for the given program.  For example:
.PP
.RS 3
.nf
 >mbs-show bridge
 -rwxrwxr-x   1 user tstapps  2771016 Feb  2 16:47 ddscan.06037183037
 -rwxrwxr-x   1 user tstapps  2771004 Feb  6 18:30 ddscan.06039112121
 -rwxrwxr-x   1 user tstapps  7733248 Feb  8 11:21 ddscan.06039120957
.fi
.RE
.PP
The startup scrips should allow you to use one of these older binaries
by specifying the extension code.  For example if you wanted to run the
ddscan.06039112121 code, then run:
.PP
.nf
.RS 3
 >ddscan old=06039112121
.RE
.fi
.SH AUTHOR
 Jerry Ehlers, \fBEPTG\fR
