#!/bin/sh
# Script to list mbs files
#
# Maintained by Jerry Ehlers under DDS
#

TSTAPPS_DIR=${DDS_DIST:-/tstapps/asi}
if [ -d /apps/asi ]; then
  APPS_DIR=/apps/asi
fi

if [ $# -eq 0 ]; then
   echo 
   echo "mbs-list lists all the binary file versions that exist within the"
   echo "${APPS_DIR} and ${TSTAPPS_DIR} structures for a particular program."
   echo
   echo "Usage: mbs-list <mbs-program-name>"
   echo 
   exit
fi

PROG=$1
APPS_FILES=''
if [ -f ${APPS_DIR}/bin/$1 ]; then
   APPS_FILES=${APPS_DIR}/bin/$1
fi
if [ -f ${APPS_DIR}/man/mbs/man1/$1.1 ]; then
   APPS_FILES="${APPS_FILES} ${APPS_DIR}/man/mbs/man1/$1.1"
fi
if [ "${APPS_FILES}." != "." ]; then
   ls -Fal ${APPS_FILES} 2> /dev/null
fi

TSTAPPS_FILES=''
if [ -f ${TSTAPPS_DIR}/bin/$1 ]; then
   TSTAPPS_FILES=${TSTAPPS_DIR}/bin/$1
fi
if [ -f ${TSTAPPS_DIR}/man/mbs/man1/$1.1 ]; then
   TSTAPPS_FILES="${TSTAPPS_FILES} ${TSTAPPS_DIR}/man/mbs/man1/$1.1"
fi
if [ "${TSTAPPS_FILES}." != "." ]; then
   ls -Fal ${TSTAPPS_FILES} 2> /dev/null
fi

ls -Fatl ${APPS_DIR}/*/*/mbs/*/*/$PROG 2> /dev/null
ls -Fatl ${TSTAPPS_DIR}/*/*/mbs/*/*/$PROG 2> /dev/null

echo 
