'\" t
.TH mbs-list 1 "$Date: 2009-01-06 10:56:43 -0600 (Tue, 06 Jan 2009) $" "DDS Utility"
.ad b
.SH NAME
mbs-list \ - Utility to list all binaries for a given program (DDS).
.SH SYNOPSIS
\fBmbs-list <program> 
.SH DESCRIPTION
\fBmbs-list\fR will list the full pathname to the startup script, the
man page, and to all the binary versions that exist for a particular program.
.SH AUTHOR
 Jerry Ehlers, \fBEPTG\fR
