'\" t
.TH mbs-which 1 "$Date: 2009-01-06 10:56:43 -0600 (Tue, 06 Jan 2009) $" "DDS Utility"
.ad b
.SH NAME
mbs-which \ - Utility to list the program binary for the current system (DDS).
.SH SYNOPSIS
\fBmbs-which <program> 
.SH DESCRIPTION
\fBmbs-which\fR will list the full pathname to the binary for the current platform that would be executed by the startup script.
.SH AUTHOR
 Jerry Ehlers, \fBEPTG\fR
