#!/bin/sh
# Script to show any old versions of DDS codes lying around
#
# Maintained by Jerry Ehlers under DDS
#

if [ $# -eq 0 ]; then
   echo 
   echo "mbs-show lists any available old binary file versions that exist"
   echo "under the save structure for a particular program."
   echo
   echo "Usage: mbs-show <mbs-program-name>"
   echo 
   exit
fi

DDS_APP=`basename $1`

DDS_APPDIR="/tstapps/global"

PROG=$DDS_APP
DIR=$DDS_APPDIR

. dds-set-path

cmd="s[${PROG}\$[unlinked[" 
OLDDIR=`echo ${APP} | sed $cmd`
cd $OLDDIR
n=`ls ${PROG}* 2> /dev/null|wc -l`
if [ $n -gt 0 ]; then
   ls -l ${PROG}*
else
   echo "no old versions available at this time on this platform for program: $PROG"
fi
