"asp.map:= $Id: asp.map.dds 228 2011-05-05 23:13:45Z user $\n"
"RCS-t=DDS, asp.map.dds\n"
"\n"
"map:in_fmt:out_fmt.out_field= expression\n"
"\n"
"\n"
"comment= SEGY to ASP trace header map.\n"
"   Derived  04/30/93 by Randy Selzler\n"
"   Modified 08/27/01 by Jerry Ehlers for segy Rev 1.0\n"
"   Modified 09/09/04 by Jerry Ehlers for su\n"
"   Modified 11/18/04 by Jerry Ehlers for seg1 as separate format\n"
"   Modified 11/01/06 by Jerry Ehlers\n"
"\n"
"map:segy:asp.SGRDat= dateint(Date)\n"
"map:segy:asp.SGRNum= MuteEnd\n"
"map:segy:asp.SGRAmp= DateType\n"
"map:segy:asp.FlReFN= Spare.Hdr.FlReFN\n"
"map:segy:asp.InStAp= SrcStatic\n"
"map:segy:asp.RcStAp= GrpStatic\n"
"map:segy:asp.ToStAp= Spare.Hdr.CdpStatic\n"
"map:segy:asp.SrPtXC= SrcX\n"
"map:segy:asp.SrPtYC= SrcY\n"
"map:segy:asp.RcPtXC= GrpX\n"
"map:segy:asp.RcPtYC= GrpY\n"
"map:segy:asp.SrRcMX= Spare.Hdr.SrRcMX\n"
"map:segy:asp.SrRcMY= Spare.Hdr.SrRcMY\n"
"map:segy:asp.CDPBCX= Spare.Hdr.CDPBCX\n"
"map:segy:asp.CDPBCY= Spare.Hdr.CDPBCY\n"
"map:segy:asp.FlDtEl= Spare.Hdr.FlDtEl\n"
"map:segy:asp.ShtDep= SrcDepth\n"
"map:segy:asp.UphlTm= UpholeTmSrc\n"
"map:segy:asp.FoldNm= HorzStack\n"
"map:segy:asp.RecNum= Spare.Hdr.RecNum\n"
"map:segy:asp.TrcNum= CdpTrcNum\n"
"map:segy:asp.SrcPnt= Spare.Hdr.SrcPnt\n"
"map:segy:asp.SrcLoc= Spare.Hdr.SrcLoc\n"
"map:segy:asp.PrRcNm= FieldRecNum\n"
"map:segy:asp.PrTrNm= FieldTrcNum\n"
"map:segy:asp.SrPtEl= SrcElev\n"
"map:segy:asp.DstUsg= Spare.Hdr.DstUsg\n"
"map:segy:asp.RecInd= Spare.Hdr.RecInd\n"
"map:segy:asp.GrpElv= GrpElev\n"
"map:segy:asp.LinInd= Spare.Hdr.LinInd\n"
"map:segy:asp.DphInd= CdpNum\n"
"map:segy:asp.DePtEl= Spare.Hdr.DePtEl\n"
"map:segy:asp.RfSrEl= GrpDatum\n"
"map:segy:asp.StaCor= TotalStatic\n"
"map:segy:asp.SoPtNm= Spare.Hdr.SoPtNm\n"
"\n"
"write:segy:asp.InTrCn= linetrc\n"
"\n"
"map:segy1:asp.SGRDat= dateint(Date)\n"
"map:segy1:asp.SGRNum= MuteEnd\n"
"map:segy1:asp.SGRAmp= DateType\n"
"map:segy1:asp.FlReFN= Spare1.Hdr.FlReFN\n"
"map:segy1:asp.InStAp= SrcStatic\n"
"map:segy1:asp.RcStAp= GrpStatic\n"
"map:segy1:asp.ToStAp= Spare1.Hdr.CdpStatic\n"
"map:segy1:asp.SrPtXC= SrcX\n"
"map:segy1:asp.SrPtYC= SrcY\n"
"map:segy1:asp.RcPtXC= GrpX\n"
"map:segy1:asp.RcPtYC= GrpY\n"
"map:segy1:asp.SrRcMX= Spare1.Hdr.SrRcMX\n"
"map:segy1:asp.SrRcMY= Spare1.Hdr.SrRcMY\n"
"map:segy1:asp.FlDtEl= Spare1.Hdr.FlDtEl\n"
"map:segy1:asp.ShtDep= SrcDepth\n"
"map:segy1:asp.UphlTm= UpholeTmSrc\n"
"map:segy1:asp.FoldNm= HorzStack\n"
"map:segy1:asp.RecNum= Spare1.Hdr.RecNum\n"
"map:segy1:asp.TrcNum= CdpTrcNum\n"
"map:segy1:asp.SrcPnt= Spare1.Hdr.SrcPnt\n"
"map:segy1:asp.PrRcNm= FieldRecNum\n"
"map:segy1:asp.PrTrNm= FieldTrcNum\n"
"map:segy1:asp.SrPtEl= SrcElev\n"
"map:segy1:asp.RecInd= Spare1.Hdr.RecInd\n"
"map:segy1:asp.GrpElv= GrpElev\n"
"#map:segy1:asp.DphInd= CdpNum\n"
"map:segy1:asp.DePtEl= Spare1.Hdr.DePtEl\n"
"map:segy1:asp.RfSrEl= GrpDatum\n"
"map:segy1:asp.StaCor= TotalStatic\n"
"map:segy1:asp.SoPtNm= Spare1.Hdr.SoPtNm\n"
"\n"
"write:segy1:asp.InTrCn= linetrc\n"
"\n"
"map:su:asp.SGRDat= dateint(Date)\n"
"map:su:asp.SGRNum= MuteEnd\n"
"map:su:asp.SGRAmp= DateType\n"
"map:su:asp.FlReFN= Spare.Hdr.FlReFN\n"
"map:su:asp.InStAp= SrcStatic\n"
"map:su:asp.RcStAp= GrpStatic\n"
"map:su:asp.ToStAp= Spare.Hdr.CdpStatic\n"
"map:su:asp.SrPtXC= SrcX\n"
"map:su:asp.SrPtYC= SrcY\n"
"map:su:asp.RcPtXC= GrpX\n"
"map:su:asp.RcPtYC= GrpY\n"
"map:su:asp.SrRcMX= Spare.Hdr.SrRcMX\n"
"map:su:asp.SrRcMY= Spare.Hdr.SrRcMY\n"
"map:su:asp.CDPBCX= Spare.Hdr.CDPBCX\n"
"map:su:asp.CDPBCY= Spare.Hdr.CDPBCY\n"
"map:su:asp.FlDtEl= Spare.Hdr.FlDtEl\n"
"map:su:asp.ShtDep= SrcDepth\n"
"map:su:asp.UphlTm= UpholeTmSrc\n"
"map:su:asp.FoldNm= HorzStack\n"
"map:su:asp.RecNum= Spare.Hdr.RecNum\n"
"map:su:asp.TrcNum= CdpTrcNum\n"
"map:su:asp.SrcPnt= Spare.Hdr.SrcPnt\n"
"map:su:asp.SrcLoc= Spare.Hdr.SrcLoc\n"
"map:su:asp.PrRcNm= FieldRecNum\n"
"map:su:asp.PrTrNm= FieldTrcNum\n"
"map:su:asp.SrPtEl= SrcElev\n"
"map:su:asp.DstUsg= Spare.Hdr.DstUsg\n"
"map:su:asp.RecInd= Spare.Hdr.RecInd\n"
"map:su:asp.GrpElv= GrpElev\n"
"map:su:asp.LinInd= Spare.Hdr.LinInd\n"
"map:su:asp.DphInd= CdpNum\n"
"map:su:asp.DePtEl= Spare.Hdr.DePtEl\n"
"map:su:asp.RfSrEl= GrpDatum\n"
"map:su:asp.StaCor= TotalStatic\n"
"map:su:asp.SoPtNm= Spare.Hdr.SoPtNm\n"
"\n"
"write:su:asp.InTrCn= linetrc\n"
"";
