"asp.fmt:= $Id: asp.fmt.dds 223 2011-04-06 21:25:42Z user $ \n"
"RCS-t=DDS, asp.fmt.dds\n"
"\n"
"fmt:ASP_TRACE= typedef void ASP_TRACE;\n"
"\n"
"fmt:*:asp=               /* root for \"asp\" format */\n"
"   typedef ASP_TRACE SEQUENCE;\n"
"   /* PREAMBLE not applicable */\n"
"   /* EPILOGUE not applicable */\n"
"fmt:*:cube=   typedef CUBE_TRACE SEQUENCE;\n"
"fmt:*:fcube=  typedef FCUBE_TRACE SEQUENCE;\n"
"fmt:*:fcubex= typedef FCUBEX_TRACE SEQUENCE;\n"
"fmt:*:dcube=  typedef DCUBE_TRACE SEQUENCE;\n"
"fmt:*:dcubex= typedef DCUBEX_TRACE SEQUENCE;\n"
"fmt:*:ccube=  typedef CCUBE_TRACE SEQUENCE;\n"
"fmt:*:ccubex= typedef CCUBEX_TRACE SEQUENCE;\n"
"fmt:*:icube=  typedef ICUBE_TRACE SEQUENCE;\n"
"fmt:*:icubex= typedef ICUBEX_TRACE SEQUENCE;\n"
"fmt:*:i2cube= typedef I2CUBE_TRACE SEQUENCE;\n"
"fmt:*:i2cubex=typedef I2CUBEX_TRACE SEQUENCE;\n"
"fmt:*:i1cube= typedef I1CUBE_TRACE SEQUENCE;\n"
"fmt:*:sep=    typedef SEP_TRACE SEQUENCE;\n"
"\n"
"fmt:asp=    typedef ASP_TRACE SEQUENCE;\n"
"fmt:cube=   typedef CUBE_TRACE SEQUENCE;\n"
"fmt:fcube=  typedef FCUBE_TRACE SEQUENCE;\n"
"fmt:fcubex= typedef FCUBEX_TRACE SEQUENCE;\n"
"fmt:dcube=  typedef DCUBE_TRACE SEQUENCE;\n"
"fmt:dcubex= typedef DCUBEX_TRACE SEQUENCE;\n"
"fmt:ccube=  typedef CCUBE_TRACE SEQUENCE;\n"
"fmt:ccubex= typedef CCUBEX_TRACE SEQUENCE;\n"
"fmt:icube=  typedef ICUBE_TRACE SEQUENCE;\n"
"fmt:icubex= typedef ICUBEX_TRACE SEQUENCE;\n"
"fmt:i2cube= typedef I2CUBE_TRACE SEQUENCE;\n"
"fmt:i2cubex=typedef I2CUBEX_TRACE SEQUENCE;\n"
"fmt:i1cube= typedef I1CUBE_TRACE SEQUENCE;\n"
"fmt:sep=    typedef SEP_TRACE SEQUENCE;\n"
"\n"
"fmt:*:asp.ASP_TRACE=           /* ASP_TRACE, given any other format */\n"
"   typedef align(1) struct {   /* structure for binary data */\n"
"         + SEQUENCE;           /* SEQUENCE members from previous format */\n"
"         - GREEN_PREFIX;\n"
"         - GREEN_SUFFIX;\n"
"         defn_value(\"default:\",\"MOD_FIELD\")  /* default changes */\n"
"         defn_value(\"par:\",\"MOD_FIELD\")      /* user changes */\n"
"         defn_value(\"override:\",\"MOD_FIELD\") /* override changes */\n"
"      } ASP_TRACE;             /* standard name for default \"trace\" */\n"
"\n"
"fmt:usp:asp.ASP_TRACE=         /* ASP_TRACE, given usp format */\n"
"   typedef align(1) struct {   /* structure for binary data */\n"
"         + SEQUENCE;           /* SEQUENCE members from previous format */\n"
"         - GREEN_PREFIX;\n"
"         - GREEN_SUFFIX;\n"
"         defn_value(\"default:\",\"MOD_FIELD\")  /* default changes */\n"
"         defn_value(\"par:\",\"MOD_FIELD\")      /* user changes */\n"
"         defn_value(\"override:\",\"MOD_FIELD\") /* override changes */\n"
"         - int usp_trace_pad;  /* garbage */\n"
"      } ASP_TRACE;             /* standard name for default \"trace\" */\n"
"\n"
"fmt:segy:asp.ASP_TRACE=\n"
"   typedef align(1) struct {\n"
"      + SEQUENCE; /* SEQUENCE members from previous format */\n"
"      - GREEN_PREFIX;\n"
"      - GREEN_SUFFIX;\n"
"      -+ int\n"
"         SGRDat,     /* Place holder for segy Date */\n"
"         SGRNum,     /* SGR number */\n"
"         SGRAmp,     /* SGR PreAmp Gain, Filter */\n"
"         FlReFN,     /* Field Record File Number */\n"
"         InStAp,     /* Initiation Static Applied */\n"
"         RcStAp,     /* Reception Static Applied */\n"
"         ToStAp,     /* Total Static Applied */\n"
"         SrPtXC,     /* Src Point X-Coordinate 3D */\n"
"         SrPtYC,     /* Src Point Y-Coordinate 3D */\n"
"         RcPtXC,     /* Rec Point X-Coordinate 3D */\n"
"         RcPtYC,     /* Rec Point Y-Coordinate 3D */\n"
"         SrRcMX,     /* Src Rec Midpoint X 3D */\n"
"         SrRcMY,     /* Src Rec Midpoint Y 3D */\n"
"         CDPBCX,     /* CDP Bin Center X Coordinate */\n"
"         CDPBCY,     /* CDP Bin Center Y Coordinate */\n"
"         InTrCn,     /* Incremental Trace Counter */\n"
"         FlDtEl,     /* Floating Datum Elev this CDP */\n"
"         ShtDep,     /* shot depth */\n"
"         UphlTm,     /* uphole time in ms */\n"
"         FoldNm,     /* fold */\n"
"         RecNum,     /* record number */\n"
"         TrcNum,     /* trace number */\n"
"         SrcPnt,     /* src point above this depth pt */\n"
"         SrcLoc,     /* src location ind mult by 10 */\n"
"         PrRcNm,     /* permanent record number PRI */\n"
"         PrTrNm,     /* permanent trace number PTI */\n"
"         SrPtEl,     /* source point elevation */\n"
"         DstUsg,     /* unsigned trace distance */\n"
"         RecInd,     /* rec location index	GI */\n"
"         DstSgn,     /* signed trace distance */\n"
"         GrpElv,     /* group elevation */\n"
"         LinInd,     /* line index 3D */\n"
"         DphInd,     /* depth index */\n"
"         DePtEl,     /* depth point elevation */\n"
"         RfSrEl,     /* reference surface elevation */\n"
"         StaCor,     /* static correction, dead 30000 */\n"
"         SoPtNm;     /* source point number */\n"
"      -+ SAMPLE_TYPE Samples[axis_size(1)]; /* time series */\n"
"         defn_value(\"default:\",\"MOD_FIELD\")  /* default changes */\n"
"         defn_value(\"par:\",\"MOD_FIELD\")      /* user changes */\n"
"         defn_value(\"override:\",\"MOD_FIELD\") /* override changes */\n"
"      - int segy_trace_pad; /* garbage */\n"
"   } ASP_TRACE;\n"
"\n"
"$fmt:segy1:asp.ASP_TRACE=fmt:segy:asp.ASP_TRACE /* ASP_TRACE, given segy1 format */\n"
"\n"
"$fmt:su:asp.ASP_TRACE= fmt:segy:asp.ASP_TRACE   /* ASP_TRACE, given su format */\n"
"\n"
"fmt:CUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} CUBE_TRACE;\n"
"fmt:FCUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} FCUBE_TRACE;\n"
"fmt:FCUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} FCUBEX_TRACE;\n"
"fmt:DCUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} DCUBE_TRACE;\n"
"fmt:DCUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} DCUBEX_TRACE;\n"
"fmt:CCUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} CCUBE_TRACE;\n"
"fmt:CCUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} CCUBEX_TRACE;\n"
"fmt:ICUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} ICUBE_TRACE;\n"
"fmt:ICUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} ICUBEX_TRACE;\n"
"fmt:I2CUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} I2CUBE_TRACE;\n"
"fmt:I2CUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} I2CUBEX_TRACE;\n"
"fmt:I1CUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} I1CUBE_TRACE;\n"
"fmt:SEP_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} SEP_TRACE;\n"
"\n"
"fmt:*:*.CUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} CUBE_TRACE;\n"
"fmt:*:*.FCUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} FCUBE_TRACE;\n"
"fmt:*:*.FCUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} FCUBEX_TRACE;\n"
"fmt:*:*.DCUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} DCUBE_TRACE;\n"
"fmt:*:*.DCUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} DCUBEX_TRACE;\n"
"fmt:*:*.CCUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} CCUBE_TRACE;\n"
"fmt:*:*.CCUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} CCUBEX_TRACE;\n"
"fmt:*:*.ICUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} ICUBE_TRACE;\n"
"fmt:*:*.ICUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} ICUBEX_TRACE;\n"
"fmt:*:*.I2CUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} I2CUBE_TRACE;\n"
"fmt:*:*.I2CUBEX_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} I2CUBEX_TRACE;\n"
"fmt:*:*.I1CUBE_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} I1CUBE_TRACE;\n"
"fmt:*:*.SEP_TRACE=\n"
"   typedef struct { SAMPLE_TYPE Samples[axis_size(1)];} SEP_TRACE;\n"
"\n"
"fmt:SEQUENCE= typedef ASP_TRACE SEQUENCE;\n"
"fmt:GREEN_PREFIX= typedef int GREEN_PREFIX;\n"
"fmt:GREEN_SUFFIX= typedef int GREEN_SUFFIX;\n"
"\n"
"comment=\n"
"*********************************************************************\n"
"********  asp or cube formats must already be defined or ************\n"
"********  it must be explicitly defined by the program.  ************\n"
"*********************************************************************\n"
"fmt:*:fcube.SAMPLE_TYPE=  typedef float4 SAMPLE_TYPE;\n"
"fmt:*:fcubex.SAMPLE_TYPE= typedef float4x SAMPLE_TYPE;\n"
"fmt:*:dcube.SAMPLE_TYPE=  typedef float8 SAMPLE_TYPE;\n"
"fmt:*:dcubex.SAMPLE_TYPE= typedef float8x SAMPLE_TYPE;\n"
"fmt:*:ccube.SAMPLE_TYPE=  typedef complex8 SAMPLE_TYPE;\n"
"fmt:*:ccubex.SAMPLE_TYPE= typedef complex8x SAMPLE_TYPE;\n"
"fmt:*:icube.SAMPLE_TYPE=  typedef integer4 SAMPLE_TYPE;\n"
"fmt:*:icubex.SAMPLE_TYPE= typedef integer4x SAMPLE_TYPE;\n"
"fmt:*:i2cube.SAMPLE_TYPE= typedef integer2 SAMPLE_TYPE;\n"
"fmt:*:i2cubex.SAMPLE_TYPE=typedef integer2x SAMPLE_TYPE;\n"
"fmt:*:i1cube.SAMPLE_TYPE= typedef integer1 SAMPLE_TYPE;\n"
"fmt:*:sep.SAMPLE_TYPE=    typedef float4 SAMPLE_TYPE;\n"
"\n"
"comment=\n"
"*********************************************************************\n"
"********  SURFER'S  GUIDE  TO  STRUCT/UNION  ENHANCEMENTS  **********\n"
"*********************************************************************\n"
"\n"
"comment= SUMMARY of STRUCT/UNION MEMBER OPERATORS\n"
"\n"
"   struct {+ aaa; - bbb; * ccc; -+ ddd; *+ eee;} xyz;\n"
"          ^^^    ^^^    ^^^    ^^^^    ^^^^\n"
"      +,  append member, if name is unique\n"
"      -,  delete member, if it exists\n"
"      *,  replace member, if it exists\n"
"      -+, delete and append member\n"
"      *+, replace or append member\n"
"\n"
"   Members are composed from left, to right.  Example:\n"
"      given:\n"
"         typedef struct {int   a, b, c;}  old_xyz;\n"
"         typedef struct {float d, e, f;}  add_xyz;\n"
"         typedef struct {void  b, e;}     drop_xyz;\n"
"      compose:\n"
"         typedef struct {+ old_xyz; + add_xyz; - drop_xyz} xyz;\n"
"      results:\n"
"         typedef struct {int a,   c; float d,   f;} xyz;\n"
"\n"
"comment=\n"
"*********************************************************************\n"
"\n"
"comment= default sort field translation\n"
" \n"
"sort:old_fmt.old_sort_field:new_fmt= new_sort_field\n"
" \n"
"sort:segy.FieldRecNum:asp= PrRcNm\n"
"sort:segy.Spare.Hdr.RecNum:asp= RecNum\n"
"sort:segy.CdpTrcNum:asp= TrcNum\n"
"sort:segy.FieldTrcNum:asp= PrTrNm\n"
"sort:segy.Spare.Hdr.SoPtNm:asp= SoPtNm\n"
"sort:segy.Spare.Hdr.RecInd:asp= RecInd\n"
"sort:segy.Spare.Hdr.SrcPnt:asp= SrcPnt\n"
"sort:segy.CdpNum:asp= DphInd\n"
"sort:segy.SrcX:asp= SrPtXC\n"
"sort:segy.SrcY:asp= SrPtYC\n"
"sort:segy.GrpX:asp= RcPtXC\n"
"sort:segy.GrpY:asp= RcPtYC\n"
"sort:segy.DstSgn:asp= DstSgn\n"
" \n"
"sort:segy1.FieldRecNum:asp= PrRcNm\n"
"sort:segy1.Spare1.Hdr.RecNum:asp= RecNum\n"
"sort:segy1.CdpTrcNum:asp= TrcNum\n"
"sort:segy1.FieldTrcNum:asp= PrTrNm\n"
"sort:segy1.Spare1.Hdr.SoPtNm:asp= SoPtNm\n"
"sort:segy1.Spare1.Hdr.RecInd:asp= RecInd\n"
"sort:segy1.Spare1.Hdr.SrcPnt:asp= SrcPnt\n"
"sort:segy1.CdpNum:asp= DphInd\n"
"sort:segy1.SrcX:asp= SrPtXC\n"
"sort:segy1.SrcY:asp= SrPtYC\n"
"sort:segy1.GrpX:asp= RcPtXC\n"
"sort:segy1.GrpY:asp= RcPtYC\n"
"sort:segy1.DstSgn:asp= DstSgn\n"
" \n"
"sort:su.FieldRecNum:asp= PrRcNm\n"
"sort:su.Spare.Hdr.RecNum:asp= RecNum\n"
"sort:su.CdpTrcNum:asp= TrcNum\n"
"sort:su.FieldTrcNum:asp= PrTrNm\n"
"sort:su.Spare.Hdr.SoPtNm:asp= SoPtNm\n"
"sort:su.Spare.Hdr.RecInd:asp= RecInd\n"
"sort:su.Spare.Hdr.SrcPnt:asp= SrcPnt\n"
"sort:su.CdpNum:asp= DphInd\n"
"sort:su.SrcX:asp= SrPtXC\n"
"sort:su.SrcY:asp= SrPtYC\n"
"sort:su.GrpX:asp= RcPtXC\n"
"sort:su.GrpY:asp= RcPtYC\n"
"sort:su.DstSgn:asp= DstSgn\n"
"";
