"segy.map:= $Id: segy1.map.dds 228 2011-05-05 23:13:45Z user $\n"
"RCS-t=DDS, segy1.map.dds\n"
"\n"
"map:in_fmt:out_fmt.out_field= expression\n"
"\n"
"map:*:segy1.TrcIdCode=   1\n"
"map:*:segy1.ElevScaler=  1\n"
"map:*:segy1.XYScaler=    1\n"
"\n"
"map:segy1:segy1.TrcIdCode=  TrcIdCode\n"
"map:segy1:segy1.ElevScaler= ElevScaler\n"
"map:segy1:segy1.XYScaler=   XYScaler\n"
"\n"
"comment= USP to SEGY1 trace header map.\n"
"   Derived  11/18/04 by Jerry Ehlers\n"
"   Modified 11/01/06 by Jerry Ehlers\n"
"\n"
"map:usp:segy1.Date=        datestruct(SGRDat)\n"
"map:usp:segy1.MuteEnd=     SGRNum\n"
"map:usp:segy1.DateType=    SGRAmp\n"
"map:usp:segy1.SrcStatic=   InStAp\n"
"map:usp:segy1.GrpStatic=   RcStAp\n"
"map:usp:segy1.SrcX=        SrPtXC\n"
"map:usp:segy1.SrcY=        SrPtYC\n"
"map:usp:segy1.GrpX=        RcPtXC\n"
"map:usp:segy1.GrpY=        RcPtYC\n"
"map:usp:segy1.SrcDepth=    ShtDep\n"
"map:usp:segy1.UpholeTmSrc= UphlTm\n"
"map:usp:segy1.HorzStack=   FoldNm\n"
"map:usp:segy1.CdpTrcNum=   TrcNum\n"
"map:usp:segy1.FieldRecNum= PrRcNm\n"
"map:usp:segy1.FieldTrcNum= PrTrNm\n"
"map:usp:segy1.SrcElev=     SrPtEl\n"
"map:usp:segy1.GrpElev=     GrpElv\n"
"#map:usp:segy1.CdpNum=      DphInd\n"
"map:usp:segy1.GrpDatum=    RfSrEl\n"
"map:usp:segy1.TotalStatic= StaCor\n"
"map:usp:segy1.TrcIdCode=   (StaCor - 30000) ? 1 : 2\n"
"\n"
"map:asp:segy1.Date=        datestruct(field(SGRDat, 0))\n"
"map:asp:segy1.MuteEnd=     field(SGRNum, nop)\n"
"map:asp:segy1.DateType=    field(SGRAmp, nop)\n"
"map:asp:segy1.SrcStatic=   field(InStAp, nop)\n"
"map:asp:segy1.GrpStatic=   field(RcStAp, nop)\n"
"map:asp:segy1.SrcX=        field(SrPtXC, nop)\n"
"map:asp:segy1.SrcY=        field(SrPtYC, nop)\n"
"map:asp:segy1.GrpX=        field(RcPtXC, nop)\n"
"map:asp:segy1.GrpY=        field(RcPtYC, nop)\n"
"map:asp:segy1.SrcDepth=    field(ShtDep, nop)\n"
"map:asp:segy1.UpholeTmSrc= field(UphlTm, nop)\n"
"map:asp:segy1.HorzStack=   field(FoldNm, nop)\n"
"map:asp:segy1.CdpTrcNum=   field(TrcNum, nop)\n"
"map:asp:segy1.FieldRecNum= field(PrRcNm, nop)\n"
"map:asp:segy1.FieldTrcNum= field(PrTrNm, nop)\n"
"map:asp:segy1.SrcElev=     field(SrPtEl, nop)\n"
"map:asp:segy1.GrpElev=     field(GrpElv, nop)\n"
"#map:asp:segy1.CdpNum=      field(DphInd, nop)\n"
"map:asp:segy1.GrpDatum=    field(RfSrEl, nop)\n"
"map:asp:segy1.TotalStatic= field(StaCor, nop)\n"
"map:asp:segy1.TrcIdCode=   (field(StaCor, 0) - 30000) ? field(TrcIdCode, 1) : 2\n"
"map:asp:segy1.ElevScaler=  field(ElevScaler, 1)\n"
"map:asp:segy1.XYScaler=    field(XYScaler, 1)\n"
"\n"
"map:segy:segy1.CDPBCX=     Spare.Hdr.CDPBCX\n"
"map:segy:segy1.CDPBCY=     Spare.Hdr.CDPBCY\n"
"map:segy:segy1.LinInd=     Spare.Hdr.LinInd\n"
"map:segy:segy1.SrcLoc=     Spare.Hdr.SrcLoc\n"
"map:segy:segy1.DphInd=     CdpNum\n"
"\n"
"map:su:segy1.CDPBCX=     Spare.Hdr.CDPBCX\n"
"map:su:segy1.CDPBCY=     Spare.Hdr.CDPBCY\n"
"map:su:segy1.LinInd=     Spare.Hdr.LinInd\n"
"map:su:segy1.SrcLoc=     Spare.Hdr.SrcLoc\n"
"map:su:segy1.DphInd=     CdpNum\n"
"";
