"segy.fmt:= $Id: segy1.fmt.dds 235 2011-08-06 22:05:10Z user $ \n"
"RCS-t=DDS, segy1.fmt.dds\n"
"\n"
"fmt:*:segy1= /* \"segy1\" format description */\n"
"   typedef SEGY_CARD   PREAMBLE;\n"
"   typedef SEGY_BINARY PREAMBLE2;\n"
"   typedef SEGY1_TRACE  SEQUENCE;\n"
"   /* EPILOGUE not applicable */\n"
"\n"
"alias:fmt:segy1= fmt:*:segy1\n"
"\n"
"fmt:*:segy1.SEGY_FmtCode=\n"
"   typedef enum2 {\n"
"      SEGY_FmtCode_float4ibm  \\= 1,\n"
"      SEGY_FmtCode_integer4   \\= 2,\n"
"      SEGY_FmtCode_integer2   \\= 3,\n"
"      SEGY_FmtCode_integer2a  \\= 4,\n"
"      SEGY_FmtCode_float4     \\= 5,\n"
"      SEGY_FmtCode_integer1   \\= 8,\n"
"   } SEGY_FmtCode;\n"
"\n"
"fmt:*:segy1.SEGY_UnitsFlag=\n"
"   typedef enum2 {\n"
"      SEGY_UnitsFlag_meters   \\= 1,\n"
"      SEGY_UnitsFlag_feet     \\= 2,\n"
"   } SEGY_UnitsFlag;\n"
"\n"
"fmt:*:segy1.SEGY_TrcIdCode=\n"
"   typedef enum2 {\n"
"      SEGY_TrcIdCode_Seismic  \\= 1,\n"
"      SEGY_TrcIdCode_Dead     \\= 2,\n"
"      SEGY_TrcIdCode_Dummy    \\= 3,\n"
"      SEGY_TrcIdCode_TimeBrk  \\= 4,\n"
"      SEGY_TrcIdCode_Uphole   \\= 5,\n"
"      SEGY_TrcIdCode_Sweep    \\= 6,\n"
"      SEGY_TrcIdCode_Timing   \\= 7,\n"
"      SEGY_TrcIdCode_WaterBrk \\= 8,\n"
"   } SEGY_TrcIdCode;\n"
"\n"
"fmt:*:segy1.SEGY_CARD=\n"
"   typedef struct {\n"
"      GREEN_PREFIX card_green_prefix;\n"
"      SEGY_CHAR card3200[40][80]; /* forty, 80 column cards */\n"
"      unsigned1 segy_card_pad[SEGY_CARD_PAD];\n"
"      GREEN_SUFFIX card_green_suffix;\n"
"   } SEGY_CARD;\n"
"\n"
"fmt:*:segy1.SEGY_BINARY=\n"
"   typedef struct {\n"
"      GREEN_PREFIX binary_green_prefix;\n"
"      SEGY_INT\n"
"         JobNum,       /* 1:4, Job identification number */\n"
"         LineNum,      /* 5:8, Line number (only one line per reel) */\n"
"         ReelNum;      /* 9:12, Reel number */\n"
"      SEGY_SHORT\n"
"         NumTrc,       /* 13:14, Number of data traces per record */\n"
"         NumAux,       /* 15:16, Number of auxiliary traces per record */\n"
"         SmpInt,       /* 17:18, Sample interval in u-sec (this reel) */\n"
"         OrigSmpInt,   /* 19:20, Sample interval in u-sec (original) */\n"
"         NumSmp,       /* 21:22, Number of samples per trace (this reel) */\n"
"         OrigNumSmp;   /* 23:24, Number of samples per trace (original) */\n"
"      SEGY_FmtCode\n"
"         FmtCode;      /* 25:26, Data sample format (1 f4ibm,2/4 i4,3 i2,5 f4, 8 i1) */\n"
"      SEGY_SHORT\n"
"         CdpFold,      /* 27:28, CDP fold (expected traces per CDP ensemble) */\n"
"         SortCode,     /* 29:30, Trace sort code (1 none, 2 CDP, 3 fold, 4 stack) */\n"
"         VertSumFlag,  /* 31:32, Vertical sum code (1 none, n sum) */\n"
"         SwpFreqStart, /* 33:34, Sweep frequency at start */\n"
"         SwpFreqEnd,   /* 35:36, Sweep frequency at end */\n"
"         SwpLength,    /* 37:38, Sweep length (m-sec) */\n"
"         SwpCode,      /* 39:40, Sweep type code (1 linear, 2 par, 3 exp) */\n"
"         SwpChan,      /* 41:42, Trace number of sweep channel */\n"
"         SwpTprStart,  /* 43:44, Sweep trace taper length in m-sec, start */\n"
"         SwpTprEnd,    /* 45:46, Sweep trace taper length in m-sec, end */\n"
"         SwpTprType,   /* 47:48, Taper type (1 linear, 2 cos^2) */\n"
"         CorrFlag,     /* 49:50, CorrFlag data traces (1 no, 2 yes) */\n"
"         GainFlag,     /* 51:52, Binary gain recovered (1 yes, 2 no) */\n"
"         AmpFlag;      /* 53:54, Amplitude recovery method (1 no, 2 sph, 3 agc) */\n"
"      SEGY_UnitsFlag\n"
"         UnitsFlag;    /* 55:56, Measurement system (1 meters, 2 feet) */\n"
"      SEGY_SHORT\n"
"         PolarityFlag, /* 57:58, Impulse signal polarity (1 neg, 2 pos) */\n"
"         VibLagFlag;   /* 59:60, Vibratory polarity code: 1-8 */\n"
"      union {  /* 61:300, Unassigned--for optional information */\n"
"         unsigned1 I1[240];\n"
"         integer2 I2[120];\n"
"         integer4 I4[60];\n"
"         float4 F4[60];\n"
"         float4ibm F4ibm[60];\n"
"      } SpareBin;\n"
"      SEGY_SHORT\n"
"         SegyFmt,      /* 301:302, Segy Format (0100x for Rev 1.0) */\n"
"         FixedLength,  /* 303:304, Fixed trace Length flag (1)*/\n"
"         NumHdr,       /* 305:306, Number of Extended Textual Headers */\n"
"         Unassigned;   /* 307:308, Unassigned */\n"
"      union {  /* 309:400, Unassigned--for optional information */\n"
"         unsigned1 I1[92];\n"
"         integer2 I2[46];\n"
"         integer4 I4[23];\n"
"         float4 F4[23];\n"
"         float4ibm F4ibm[23];\n"
"      } Spare2Bin;\n"
"      unsigned1 segy_binary_pad[SEGY_BINARY_PAD];\n"
"      GREEN_SUFFIX binary_green_suffix;\n"
"   } SEGY_BINARY;\n"
"\n"
"\n"
"fmt:*:segy1.SEGY1_TRACE=\n"
"   typedef align(1) struct {\n"
"      GREEN_PREFIX green_prefix;\n"
"      SEGY_INT\n"
"         LineTrcNum,     /* 1:4, Trace sequence number within line */\n"
"         ReelTrcNum,     /* 5:8, Trace sequence number within reel */\n"
"         FieldRecNum,    /* 9:12, Original field record number */\n"
"         FieldTrcNum,    /* 13:16, Trace number within the original field rec */\n"
"         SrcPtNum,       /* 17:20, Energy source point number */\n"
"         CdpNum,         /* 21:24, CDP ensemble number */\n"
"         CdpTrcNum;      /* 25:28, Trace number within the CDP ensemble */\n"
"    /*  SEGY_TrcIdCode */\n"
"      SEGY_SHORT\n"
"         TrcIdCode;      /* 29:30, Trace identification code: 1-8 */\n"
"      SEGY_SHORT\n"
"         VertStack,      /* 31:32, Number of vertically summed traces */\n"
"         HorzStack,      /* 33:34, Number of horizontally stacked traces */\n"
"         DataUse;        /* 35:36, Data use (1 production, 2 test) */\n"
"      SEGY_INT\n"
"         DstSgn,         /* 37:40, Distance from source to group, signed */\n"
"         GrpElev,        /* 41:44, Receiver group elevation */\n"
"         SrcElev,        /* 45:48, Surface elevation at source */\n"
"         SrcDepth,       /* 49:52, Source depth below surface (positive) */\n"
"         GrpDatum,       /* 53:56, Datum elevation at receiver group */\n"
"         SrcDatum,       /* 57:60, Datum elevation at source */\n"
"         WatDepthSrc,    /* 61:64, Water depth at source */\n"
"         WatDepthGrp;    /* 65:68, Water depth at group */\n"
"      SEGY_SHORT\n"
"         ElevScaler,     /* 69:70, Scalar to be applied to all elevations */\n"
"         XYScaler;       /* 71:72, Scalar to be applied to all coordinates */\n"
"      SEGY_INT\n"
"         SrcX,           /* 73:76, Source coordinate X */\n"
"         SrcY,           /* 77:80, Source coordinate Y */\n"
"         GrpX,           /* 81:84, Group coordinate X */\n"
"         GrpY;           /* 85:88, Group coordinate Y */\n"
"      SEGY_SHORT\n"
"         XYUnits,        /* 89:90, Coordinate units (1 length, 2 arc sec) */\n"
"         WeathVel,       /* 91:92, Weathering velocity */\n"
"         SubWeathVel,    /* 93:94, Subweathering velocity */\n"
"         UpholeTmSrc,    /* 95:96, Uphole time at source */\n"
"         UpholeTmGrp,    /* 97:98, Uphole time at group */\n"
"         SrcStatic,      /* 99:100, Source static correction */\n"
"         GrpStatic,      /* 101:102, Group static correction */\n"
"         TotalStatic,    /* 103:104, Total static applied */\n"
"         LagTmBreak,     /* 105:106, Lag time A. Time in ms */\n"
"         LagTmSrc,       /* 107:108, Lag time B. Time in ms */\n"
"         LagTmSmpOne,    /* 109:110, Delay recording time. Time in ms */\n"
"         MuteStart,      /* 111:112, Mute time--start */\n"
"         MuteEnd,        /* 113:114, Mute time--end */\n"
"         TrcNumSmp,      /* 115:116, Number of samples in this trace */\n"
"         TrcSmpInt,      /* 117:118, Sample interval in us for this trace */\n"
"         GainType,       /* 119:120, Gain type of field instruments: 1-4 */\n"
"         GainConst,      /* 121:122, Instrument gain constant */\n"
"         GainInit,       /* 123:124, Instrument early or initial gain (db) */\n"
"         CorrFlag,       /* 125:126, CorrFlag data traces (1 no, 2 yes) */\n"
"         SwpFreqStart,   /* 127:128, Sweep frequency at start */\n"
"         SwpFreqEnd,     /* 129:130, Sweep frequency at end */\n"
"         SwpLength,      /* 131:132, Sweep length in ms */\n"
"         SwpType,        /* 133:134, Sweep type (1 linear, 2 par, 3 exp, 4 ?) */\n"
"         SwpTprStart,    /* 135:136, Sweep trace taper length at start in ms */\n"
"         SwpTprEnd,      /* 137:138, Sweep trace taper length at end in ms */\n"
"         SwpTprType,     /* 139:140, Taper type (1 linear, 2 cos^2, 3 other) */\n"
"         AntiAliasFreq,  /* 141:142, Alias filter frequency, if used */\n"
"         AntiAliasSlope, /* 143:144, Alias filter slope */\n"
"         NotchFreq,      /* 145:146, Notch filter frequency, if used */\n"
"         NotchSlope,     /* 147:148, Notch filter slope */\n"
"         LowCutFreq,     /* 149:150, Low cut frequency, if used */\n"
"         HighCutFreq,    /* 151:152, High cut frequency, if used */\n"
"         LowCutSlope,    /* 153:154, Low cut slope */\n"
"         HighCutSlope;   /* 155:156, High cut slope */\n"
"      struct {  /* Date information */\n"
"         SEGY_SHORT\n"
"            DateYear,    /* 157:158, Year data recorded */\n"
"            DateDay,     /* 159:160, Day of year */\n"
"            DateHour,    /* 161:162, Hour of day (24 hour clock) */\n"
"            DateMin,     /* 163:164, Minute of hour */\n"
"            DateSec;     /* 165:166, Second of minute */\n"
"      } Date;\n"
"      SEGY_SHORT\n"
"         DateType,       /* 167:168, Time basis code (1 local, 2 gmt, 3 other) */\n"
"         TrcWeight,      /* 169:170, Trace weighting factor */\n"
"         RollSwtch1,     /* 171:172, Geophone group number of roll switch pos 1 */\n"
"         RollTrace1,     /* 173:174, Geophone group number of trace number one */\n"
"         RollTraceN,     /* 175:176, Geophone group number of last trace */\n"
"         RollGapSize,    /* 177:178, Gap size (total number of groups dropped) */\n"
"         OverTravel;     /* 179:180, Overtravel associated with taper */\n"
"      SEGY_INT\n"
"         CDPBCX,         /* 181:184, CDP Bin Center X coordinate */\n"
"         CDPBCY,         /* 185:188, CDP Bin Center Y coordinate */\n"
"         LinInd,         /* 189:192, Line Index */\n"
"         DphInd,         /* 193:196, Depth Index (crossline index) */\n"
"         SrcLoc;         /* 197:200, Source Index times 10 */\n"
"      SEGY_SHORT\n"
"         SrcLocScaler,   /* 201:202, Source Index scaler (-10) */\n"
"         TrcUnit;        /* 203:204, Trace value measurement unit */\n"
"      SEGY_INT\n"
"         TranConstMan;   /* 205:208, Transduction Constant (mantissa) */\n"
"      SEGY_SHORT\n"
"         TranConstExp,   /* 209:210, Transduction Constant (exponent) */\n"
"         TranUnits,      /* 211:212, Transduction Units */\n"
"         DevId,          /* 213:214, Device/Trace Identifier */\n"
"         MsecScaler;     /* 215:216, Scalar to be applied to times */\n"
"      union {  /* Unassigned--for optional information */\n"
"         unsigned1 I1[24];\n"
"         integer2 I2[12];\n"
"         integer4 I4[6];\n"
"         float4 F4[6];\n"
"         float4ibm F4ibm[6];\n"
"         struct {\n"
"            SEGY_INT\n"
"               SrRcMX,    /* 217:220, Source to Receiver Mid Point X co-ordinate */\n"
"               SrRcMY;    /* 221:224, Source to Receiver Mid Point Y co-ordinate */\n"
"            SEGY_SHORT\n"
"               SrcPnt,    /* 225:226, src point above this depth pt */\n"
"               SoPtNm,    /* 227:228, source point number */\n"
"               RecInd,    /* 229:230, rec location index GI */\n"
"               RecNum,    /* 231:232, USP RecNum */\n"
"               FlReFN,    /* 233:234, USP FlReFN */\n"
"               CdpStatic, /* 235:236, Dons famous Cdp Static USP ToStAp */\n"
"               DePtEl,    /* 237:238, Depth Point Elevation */\n"
"               FlDtEl;    /* 239:240, Floating Datum Elevation */\n"
"         } Hdr;\n"
"      } Spare1;\n"
"      SAMPLE_TYPE Samples[axis_size(1)]; /* time series */\n"
"      unsigned1 segy_trace_pad[SEGY_TRACE_PAD];\n"
"      GREEN_SUFFIX green_suffix;\n"
"   } SEGY1_TRACE;\n"
"\n"
"comment= default sort field translation\n"
"\n"
"sort:usp.PrRcNm:segy1= FieldRecNum\n"
"sort:usp.FlReFN:segy1= Spare1.Hdr.FlReFN\n"
"sort:usp.RecNum:segy1= Spare1.Hdr.RecNum\n"
"sort:usp.SrcPnt:segy1= Spare1.Hdr.SrcPnt\n"
"sort:usp.SoPtNm:segy1= Spare1.Hdr.SoPtNm\n"
"sort:usp.RecInd:segy1= Spare1.Hdr.RecInd\n"
"sort:usp.LinInd:segy1= LinInd\n"
"sort:usp.SrcLoc:segy1= SrcLoc\n"
"sort:usp.DphInd:segy1= CdpNum\n"
"sort:usp.TrcNum:segy1= CdpTrcNum\n"
"sort:usp.PrTrNm:segy1= FieldTrcNum\n"
"sort:usp.SrPtXC:segy1= SrcX\n"
"sort:usp.SrPtYC:segy1= SrcY\n"
"sort:usp.RcPtXC:segy1= GrpX\n"
"sort:usp.RcPtYC:segy1= GrpY\n"
"\n"
"sort:asp.PrRcNm:segy1= FieldRecNum\n"
"sort:asp.FlReFN:segy1= Spare1.Hdr.FlReFN\n"
"sort:asp.RecNum:segy1= Spare1.Hdr.RecNum\n"
"sort:asp.SrcPnt:segy1= Spare1.Hdr.SrcPnt\n"
"sort:asp.SoPtNm:segy1= Spare1.Hdr.SoPtNm\n"
"sort:asp.RecInd:segy1= Spare1.Hdr.RecInd\n"
"sort:asp.LinInd:segy1= LinInd\n"
"sort:asp.SrcLoc:segy1= SrcLoc\n"
"sort:asp.DphInd:segy1= CdpNum\n"
"sort:asp.TrcNum:segy1= CdpTrcNum\n"
"sort:asp.PrTrNm:segy1= FieldTrcNum\n"
"sort:asp.SrPtXC:segy1= SrcX\n"
"sort:asp.SrPtYC:segy1= SrcY\n"
"sort:asp.RcPtXC:segy1= GrpX\n"
"sort:asp.RcPtYC:segy1= GrpY\n"
"\n"
"sort:segy.Spare.Hdr.LinInd:segy1= LinInd\n"
"sort:segy.Spare.Hdr.SrcLoc:segy1= SrcLoc\n"
"\n"
"comment= the following are created explicitly by \"open\".\n"
"  \n"
"xfmt:*:segy.SEGY_ADJUST= /* SEGY format adjustments */\n"
"   typedef enum {\n"
"      SEGY_CARD_PAD \\= 0,      /* byte size of card header pad */\n"
"      SEGY_BINARY_PAD \\= 0,    /* byte size of binary header pad */\n"
"      SEGY_TRACE_PAD \\= 0,     /* byte size of trace pad */\n"
"   } SEGY_ADJUST;\n"
"\n"
"fmt:SEGY_CHAR=   typedef ascii1 SEGY_CHAR;\n"
"fmt:SEGY_SHORT=  typedef integer2 SEGY_SHORT;\n"
"fmt:SEGY_INT=    typedef integer4 SEGY_INT;\n"
"fmt:SEGY_FLOAT=  typedef float4 SEGY_FLOAT;\n"
"fmt:SAMPLE_TYPE= typedef float4ibm SAMPLE_TYPE;\n"
"";
