"usp.map:= $Id: usp.map.dds 228 2011-05-05 23:13:45Z user $\n"
"RCS-t=DDS, usp.map.dds\n"
"\n"
"map:in_fmt:out_fmt.out_field= expression\n"
"\n"
"write:usp.line_green_prefix= sizeof(USP_LINE) - sizeof(USP_INT)\n"
"write:usp.green_prefix= sizeof(USP_TRACE) - sizeof(USP_INT)\n"
"\n"
"###write:usp.InTrCn= linetrc()\n"
"\n"
"comment= SEGY to USP trace header map.\n"
"   Derived  04/30/93 by Randy Selzler\n"
"   Modified 08/27/01 by Jerry Ehlers for segy Rev 1.0\n"
"   Modified 09/09/04 by Jerry Ehlers for su\n"
"\n"
"comment= Colorado School of Mines mapping\n"
"###this fails... first expression is not constant ?\n"
"###map:segy:usp.StaCor= (TrcIdCode equals 2) ? 30000 : TotalStatic\n"
"map:segy:usp.StaCor= TotalStatic\n"
"map:segy:usp.RcStAp= GrpStatic\n"
"map:segy:usp.InStAp= SrcStatic\n"
"map:segy:usp.ToStAp= field(Spare.Hdr.CdpStatic, nop)\n"
"map:segy:usp.SGRNum= MuteEnd\n"
"map:segy:usp.UphlTm= UpholeTmSrc\n"
"map:segy:usp.ShtDep= SrcDepth\n"
"map:segy:usp.TrcNum= CdpTrcNum\n"
"map:segy:usp.DphInd= CdpNum\n"
"map:segy:usp.PrTrNm= FieldTrcNum\n"
"map:segy:usp.FoldNm= HorzStack\n"
"map:segy:usp.RfSrEl= GrpDatum\n"
"map:segy:usp.GrpElv= GrpElev\n"
"map:segy:usp.SrPtEl= SrcElev\n"
"map:segy:usp.PrRcNm= FieldRecNum\n"
"map:segy:usp.SrPtXC= SrcX\n"
"map:segy:usp.SrPtYC= SrcY\n"
"map:segy:usp.RcPtXC= GrpX\n"
"map:segy:usp.RcPtYC= GrpY\n"
"map:segy:usp.SGRDat= dateint(Date)\n"
"map:segy:usp.SGRAmp= DateType\n"
"map:segy:usp.CDPBCX= field(ident(\"Spare.Hdr.CDPBCX\"), nop)\n"
"map:segy:usp.CDPBCY= field(ident(\"Spare.Hdr.CDPBCY\"), nop)\n"
"map:segy:usp.LinInd= field(ident(\"Spare.Hdr.LinInd\"), nop)\n"
"map:segy:usp.SrcLoc= field(ident(\"Spare.Hdr.SrcLoc\"), nop)\n"
"map:segy:usp.SrRcMX= field(ident(\"Spare.Hdr.SrRcMX\"), nop)\n"
"map:segy:usp.SrRcMY= field(ident(\"Spare.Hdr.SrRcMY\"), nop)\n"
"map:segy:usp.SrcPnt= field(ident(\"Spare.Hdr.SrcPnt\"), nop)\n"
"map:segy:usp.SoPtNm= field(ident(\"Spare.Hdr.SoPtNm\"), nop)\n"
"map:segy:usp.RecInd= field(ident(\"Spare.Hdr.RecInd\"), nop)\n"
"map:segy:usp.RecNum= field(ident(\"Spare.Hdr.RecNum\"), nop)\n"
"map:segy:usp.FlReFN= field(ident(\"Spare.Hdr.FlReFN\"), nop)\n"
"map:segy:usp.ToStAp= field(ident(\"Spare.Hdr.CdpStatic\"), nop)\n"
"map:segy:usp.DePtEl= field(ident(\"Spare.Hdr.DePtEl\"), nop)\n"
"map:segy:usp.FlDtEl= field(ident(\"Spare.Hdr.FlDtEl\"), nop)\n"
"\n"
"map:segy1:usp.StaCor= TotalStatic\n"
"map:segy1:usp.RcStAp= GrpStatic\n"
"map:segy1:usp.InStAp= SrcStatic\n"
"map:segy1:usp.ToStAp= field(Spare1.Hdr.CdpStatic, nop)\n"
"map:segy1:usp.SGRNum= MuteEnd\n"
"map:segy1:usp.UphlTm= UpholeTmSrc\n"
"map:segy1:usp.ShtDep= SrcDepth\n"
"map:segy1:usp.TrcNum= CdpTrcNum\n"
"#map:segy1:usp.DphInd= CdpNum\n"
"map:segy1:usp.PrTrNm= FieldTrcNum\n"
"map:segy1:usp.FoldNm= HorzStack\n"
"map:segy1:usp.RfSrEl= GrpDatum\n"
"map:segy1:usp.GrpElv= GrpElev\n"
"map:segy1:usp.SrPtEl= SrcElev\n"
"map:segy1:usp.PrRcNm= FieldRecNum\n"
"map:segy1:usp.SrPtXC= SrcX\n"
"map:segy1:usp.SrPtYC= SrcY\n"
"map:segy1:usp.RcPtXC= GrpX\n"
"map:segy1:usp.RcPtYC= GrpY\n"
"map:segy1:usp.SGRDat= dateint(Date)\n"
"map:segy1:usp.SGRAmp= DateType\n"
"map:segy1:usp.SrRcMX= field(ident(\"Spare1.Hdr.SrRcMX\"), nop)\n"
"map:segy1:usp.SrRcMY= field(ident(\"Spare1.Hdr.SrRcMY\"), nop)\n"
"map:segy1:usp.SrcPnt= field(ident(\"Spare1.Hdr.SrcPnt\"), nop)\n"
"map:segy1:usp.SoPtNm= field(ident(\"Spare1.Hdr.SoPtNm\"), nop)\n"
"map:segy1:usp.RecInd= field(ident(\"Spare1.Hdr.RecInd\"), nop)\n"
"map:segy1:usp.RecNum= field(ident(\"Spare1.Hdr.RecNum\"), nop)\n"
"map:segy1:usp.FlReFN= field(ident(\"Spare1.Hdr.FlReFN\"), nop)\n"
"map:segy1:usp.ToStAp= field(ident(\"Spare1.Hdr.CdpStatic\"), nop)\n"
"map:segy1:usp.DePtEl= field(ident(\"Spare1.Hdr.DePtEl\"), nop)\n"
"map:segy1:usp.FlDtEl= field(ident(\"Spare1.Hdr.FlDtEl\"), nop)\n"
"\n"
"map:su:usp.StaCor= TotalStatic\n"
"map:su:usp.RcStAp= GrpStatic\n"
"map:su:usp.InStAp= SrcStatic\n"
"map:su:usp.ToStAp= field(Spare.Hdr.CdpStatic, nop)\n"
"map:su:usp.SGRNum= MuteEnd\n"
"map:su:usp.UphlTm= UpholeTmSrc\n"
"map:su:usp.ShtDep= SrcDepth\n"
"map:su:usp.TrcNum= CdpTrcNum\n"
"map:su:usp.DphInd= CdpNum\n"
"map:su:usp.PrTrNm= FieldTrcNum\n"
"map:su:usp.FoldNm= HorzStack\n"
"map:su:usp.RfSrEl= GrpDatum\n"
"map:su:usp.GrpElv= GrpElev\n"
"map:su:usp.SrPtEl= SrcElev\n"
"map:su:usp.PrRcNm= FieldRecNum\n"
"map:su:usp.SrPtXC= SrcX\n"
"map:su:usp.SrPtYC= SrcY\n"
"map:su:usp.RcPtXC= GrpX\n"
"map:su:usp.RcPtYC= GrpY\n"
"map:su:usp.SGRDat= dateint(Date)\n"
"map:su:usp.SGRAmp= DateType\n"
"map:su:usp.CDPBCX= field(ident(\"Spare.Hdr.CDPBCX\"), nop)\n"
"map:su:usp.CDPBCY= field(ident(\"Spare.Hdr.CDPBCY\"), nop)\n"
"map:su:usp.LinInd= field(ident(\"Spare.Hdr.LinInd\"), nop)\n"
"map:su:usp.SrcLoc= field(ident(\"Spare.Hdr.SrcLoc\"), nop)\n"
"map:su:usp.SrRcMX= field(ident(\"Spare.Hdr.SrRcMX\"), nop)\n"
"map:su:usp.SrRcMY= field(ident(\"Spare.Hdr.SrRcMY\"), nop)\n"
"map:su:usp.SrcPnt= field(ident(\"Spare.Hdr.SrcPnt\"), nop)\n"
"map:su:usp.SoPtNm= field(ident(\"Spare.Hdr.SoPtNm\"), nop)\n"
"map:su:usp.RecInd= field(ident(\"Spare.Hdr.RecInd\"), nop)\n"
"map:su:usp.RecNum= field(ident(\"Spare.Hdr.RecNum\"), nop)\n"
"map:su:usp.FlReFN= field(ident(\"Spare.Hdr.FlReFN\"), nop)\n"
"map:su:usp.ToStAp= field(ident(\"Spare.Hdr.CdpStatic\"), nop)\n"
"map:su:usp.DePtEl= field(ident(\"Spare.Hdr.DePtEl\"), nop)\n"
"map:su:usp.FlDtEl= field(ident(\"Spare.Hdr.FlDtEl\"), nop)\n"
"";
