##############################################
###   Copyright (C) 2009                   ###
###   BP America, Inc. Houston, TX         ###
###   Jerry Ehlers, Jan 2009               ###
##############################################
# $Id: Makefile 18 2009-01-06 22:44:01Z user $

include $(DDSROOT)/etc/MakeSrcMacro

include $(DDSROOT)/etc/MakeSrcRules

