##############################################
###   Copyright (C) 1997                   ###
###   AMOCO Corporation, Tulsa, OK 74102   ###
###   Randy Selzler, 25 Feb 1997           ###
##############################################
# $Id: Makefile 13 2009-01-06 16:56:43Z user $

include $(DDSROOT)/etc/MakeSrcMacro

include $(DDSROOT)/etc/MakeSrcRules

