/*
RCS-t=DDS, list of OP CODE definitions for expressions
 
$Id: dds_oplist.h 50 2009-02-10 21:29:01Z user $
*/

/*******************************************************************/
/* This is a list of OP CODE definitions for expressions.          */
/* The list is used to build DDS_OPCODE and DDS_OPNOTE.            */
/* The following macros must be defined prior to using the list.   */
/*    DDS_OPDEF(NAME, FLAG, ARGS, PREC, PREFIX, INFIX, SUFFIX)     */
/*                                                                 */
/* ASSIGN_OP is used for the generic assignment operator.          */
/*    Assignment expressions use a special type, DDS_EXPRA.        */
/*    Special arguments specify LHS and RHS stream types.          */
/* COPY_OP is created only by ddsMapOptimize, when it collapses    */
/*    an ASSIGN_OP into COPY_OP.                                   */
/*    ddsMapOptimize may extend the length of an existing COPY_OP  */
/*    if a subsequent ASSIGN_OP can be merged with it.             */
/*******************************************************************/

DDS_OPDEF(ASSIGN_OP,         DDS_OPNOTE_VV | ARG12XX, 2, 2, "", "=", "")
DDS_OPDEF(COPY_OP,                           ARG12XX, 3,  0, "copy", "", "")
DDS_OPDEF(ARRAY_REF_OP_PTR_SUB,           ARG1XXX, 2, 15, "", "[", "]")
   DDS_OPDEF(ARRAY_REF_OP_SUB_PTR,           ARGX2XX, 2, 15, "[", "]", "")
DDS_OPDEF(STRUCT_POINTER_OP,              ARG1XXX, 2, 15, "", "->", "")
DDS_OPDEF(STRUCT_MEMBER_OP,               ARG1XXX, 2, 15, "", ".", "")
DDS_OPDEF(UNARY_PLUS_OP,                  ARG1XXX, 1, 14, "+", "", "")
DDS_OPDEF(UNARY_MINUS_OP_INT,             ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_LONG,            ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_LLONG,           ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_UINT,            ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_ULONG,           ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_ULLONG,          ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_FLOAT,           ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_DOUBLE,          ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_LDOUBLE,         ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_CPX,             ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_DBLCPX,          ARG1XXX, 1, 14, "-", "", "")
   DDS_OPDEF(UNARY_MINUS_OP_LDBLCPX,         ARG1XXX, 1, 14, "-", "", "")
DDS_OPDEF(COMPLEMENT_OP_INT,              ARG1XXX, 1, 14, " ~", "", "")
   DDS_OPDEF(COMPLEMENT_OP_LONG,             ARG1XXX, 1, 14, " ~", "", "")
   DDS_OPDEF(COMPLEMENT_OP_LLONG,            ARG1XXX, 1, 14, " ~", "", "")
   DDS_OPDEF(COMPLEMENT_OP_UINT,             ARG1XXX, 1, 14, " ~", "", "")
   DDS_OPDEF(COMPLEMENT_OP_ULONG,            ARG1XXX, 1, 14, " ~", "", "")
   DDS_OPDEF(COMPLEMENT_OP_ULLONG,           ARG1XXX, 1, 14, " ~", "", "")
DDS_OPDEF(NEGATION_OP_CHAR,               ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_SHORT,              ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_INT,                ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_LONG,               ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_LLONG,              ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_FLOAT,              ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_DOUBLE,             ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_LDOUBLE,            ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_CPX,                ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_DBLCPX,             ARG1XXX, 1, 14, " !", "", "")
   DDS_OPDEF(NEGATION_OP_LDBLCPX,            ARG1XXX, 1, 14, " !", "", "")
DDS_OPDEF(SIZEOF_EXPR_OP,                 ARG1XXX, 1, 14,"sizeof", "", "")
DDS_OPDEF(SIZEOF_TYPE_OP,                 ARG1XXX, 1, 14,"sizeof(", "", ")")
DDS_OPDEF(AXIS_SIZE_OP,                   ARG1XXX, 1, 14,"axis_size(","",")")
DDS_OPDEF(IDENT_OP,                       ARG1XXX, 1, 14,"ident(","",")")
DDS_OPDEF(FIELD_OP,                       ARGX2XX, 1, 14,"field(",",",")")
DDS_OPDEF(EXIST_OP,                       ARG1XXX, 1, 14,"exist(","",")")
DDS_OPDEF(ORDINAL_OP,                     ARG1XXX, 1, 14,"ordinal(","",")")
DDS_OPDEF(SQRT_OP,                        ARG1XXX, 1, 14,"sqrt(","",")")
DDS_OPDEF(SIN_OP,                         ARG1XXX, 1, 14,"sin(","",")")
DDS_OPDEF(COS_OP,                         ARG1XXX, 1, 14,"cos(","",")")
DDS_OPDEF(TAN_OP,                         ARG1XXX, 1, 14,"tan(","",")")
DDS_OPDEF(ASIN_OP,                        ARG1XXX, 1, 14,"asin(","",")")
DDS_OPDEF(ACOS_OP,                        ARG1XXX, 1, 14,"acos(","",")")
DDS_OPDEF(ATAN_OP,                        ARG1XXX, 1, 14,"atan(","",")")
DDS_OPDEF(ATAN2_OP,                       ARG1XXX, 2, 14,"atan2(",",",")")
DDS_OPDEF(EXP_OP,                         ARG1XXX, 1, 14,"exp(","",")")
DDS_OPDEF(LOG_OP,                         ARG1XXX, 1, 14,"log(","",")")
DDS_OPDEF(LOG10_OP,                       ARG1XXX, 1, 14,"log10(","",")")
DDS_OPDEF(POW_OP,                         ARG12XX, 2, 14,"pow(",",",")")
DDS_OPDEF(ABS_OP,                         ARG1XXX, 1, 14,"abs(","",")")
DDS_OPDEF(SIGN_OP,                        ARG1XXX, 1, 14,"sign(","",")")
DDS_OPDEF(CEIL_OP,                        ARG1XXX, 1, 14,"ceil(","",")")
DDS_OPDEF(FLOOR_OP,                       ARG1XXX, 1, 14,"floor(","",")")
DDS_OPDEF(DATEINT_OP,                     ARG1XXX, 1, 14,"dateint(","",")")
DDS_OPDEF(DATESTRUCT_OP,                  ARG1XXX, 1, 14,"datestruct(","",")")
DDS_OPDEF(LINE_TRC_OP,                    ARGXXXX, 0, 14,"linetrc()","","")
DDS_OPDEF(REEL_TRC_OP,                    ARGXXXX, 0, 14,"reeltrc()","","")
DDS_OPDEF(MULTIPLY_OP_INT,                ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_LONG,               ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_LLONG,              ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_UINT,               ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_ULONG,              ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_ULLONG,             ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_FLOAT,              ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_DOUBLE,             ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_LDOUBLE,            ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_CPX,                ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_DBLCPX,             ARG12XX, 2, 13, "", "*", "")
   DDS_OPDEF(MULTIPLY_OP_LDBLCPX,            ARG12XX, 2, 13, "", "*", "")
DDS_OPDEF(DIVIDE_OP_INT,                  ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_LONG,                 ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_LLONG,                ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_UINT,                 ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_ULONG,                ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_ULLONG,               ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_FLOAT,                ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_DOUBLE,               ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_LDOUBLE,              ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_CPX,                  ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_DBLCPX,               ARG12XX, 2, 13, "", "/", "")
   DDS_OPDEF(DIVIDE_OP_LDBLCPX,              ARG12XX, 2, 13, "", "/", "")
DDS_OPDEF(MODULO_OP_INT,                  ARG12XX, 2, 13, "", "%", "")
   DDS_OPDEF(MODULO_OP_LONG,                 ARG12XX, 2, 13, "", "%", "")
   DDS_OPDEF(MODULO_OP_LLONG,                ARG12XX, 2, 13, "", "%", "")
   DDS_OPDEF(MODULO_OP_UINT,                 ARG12XX, 2, 13, "", "%", "")
   DDS_OPDEF(MODULO_OP_ULONG,                ARG12XX, 2, 13, "", "%", "")
   DDS_OPDEF(MODULO_OP_ULLONG,               ARG12XX, 2, 13, "", "%", "")
DDS_OPDEF(PLUS_OP_INT,                    ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_LONG,                   ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_LLONG,                  ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_UINT,                   ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_ULONG,                  ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_ULLONG,                 ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_FLOAT,                  ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_DOUBLE,                 ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_LDOUBLE,                ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_CPX,                    ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_DBLCPX,                 ARG12XX, 2, 12, "", "+", "")
   DDS_OPDEF(PLUS_OP_LDBLCPX,                ARG12XX, 2, 12, "", "+", "")
DDS_OPDEF(MINUS_OP_INT,                   ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_LONG,                  ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_LLONG,                 ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_UINT,                  ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_ULONG,                 ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_ULLONG,                ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_FLOAT,                 ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_DOUBLE,                ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_LDOUBLE,               ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_CPX,                   ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_DBLCPX,                ARG12XX, 2, 12, "", "-", "")
   DDS_OPDEF(MINUS_OP_LDBLCPX,               ARG12XX, 2, 12, "", "-", "")
DDS_OPDEF(LEFT_SHIFT_OP_INT,              ARG12XX, 2, 11, "", "<<", "")
   DDS_OPDEF(LEFT_SHIFT_OP_LONG,             ARG12XX, 2, 11, "", "<<", "")
   DDS_OPDEF(LEFT_SHIFT_OP_LLONG,            ARG12XX, 2, 11, "", "<<", "")
   DDS_OPDEF(LEFT_SHIFT_OP_UINT,             ARG12XX, 2, 11, "", "<<", "")
   DDS_OPDEF(LEFT_SHIFT_OP_ULONG,            ARG12XX, 2, 11, "", "<<", "")
   DDS_OPDEF(LEFT_SHIFT_OP_ULLONG,           ARG12XX, 2, 11, "", "<<", "")
DDS_OPDEF(RIGHT_SHIFT_OP_INT,             ARG12XX, 2, 11, "", ">>", "")
   DDS_OPDEF(RIGHT_SHIFT_OP_LONG,            ARG12XX, 2, 11, "", ">>", "")
   DDS_OPDEF(RIGHT_SHIFT_OP_LLONG,           ARG12XX, 2, 11, "", ">>", "")
   DDS_OPDEF(RIGHT_SHIFT_OP_UINT,            ARG12XX, 2, 11, "", ">>", "")
   DDS_OPDEF(RIGHT_SHIFT_OP_ULONG,           ARG12XX, 2, 11, "", ">>", "")
   DDS_OPDEF(RIGHT_SHIFT_OP_ULLONG,          ARG12XX, 2, 11, "", ">>", "")
DDS_OPDEF(LESS_THAN_OP_INT,               ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_LONG,              ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_LLONG,             ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_UINT,              ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_ULONG,             ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_ULLONG,            ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_FLOAT,             ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_DOUBLE,            ARG12XX, 2, 10, "", "<", "")
   DDS_OPDEF(LESS_THAN_OP_LDOUBLE,           ARG12XX, 2, 10, "", "<", "")
DDS_OPDEF(GREATER_THAN_OP_INT,            ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_LONG,           ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_LLONG,          ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_UINT,           ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_ULONG,          ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_ULLONG,         ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_FLOAT,          ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_DOUBLE,         ARG12XX, 2, 10, "", ">", "")
   DDS_OPDEF(GREATER_THAN_OP_LDOUBLE,        ARG12XX, 2, 10, "", ">", "")
DDS_OPDEF(LESS_EQUAL_OP_INT,              ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_LONG,             ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_LLONG,            ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_UINT,             ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_ULONG,            ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_ULLONG,           ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_FLOAT,            ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_DOUBLE,           ARG12XX, 2, 10, "", "<=", "")
   DDS_OPDEF(LESS_EQUAL_OP_LDOUBLE,          ARG12XX, 2, 10, "", "<=", "")
DDS_OPDEF(GREATER_EQUAL_OP_INT,           ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_LONG,          ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_LLONG,         ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_UINT,          ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_ULONG,         ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_ULLONG,        ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_FLOAT,         ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_DOUBLE,        ARG12XX, 2, 10, "", ">=", "")
   DDS_OPDEF(GREATER_EQUAL_OP_LDOUBLE,       ARG12XX, 2, 10, "", ">=", "")
DDS_OPDEF(EQUAL_TO_OP_INT,                ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_LONG,               ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_LLONG,              ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_UINT,               ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_ULONG,              ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_ULLONG,             ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_FLOAT,              ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_DOUBLE,             ARG12XX, 2,  9, "", "==", "")
   DDS_OPDEF(EQUAL_TO_OP_LDOUBLE,            ARG12XX, 2,  9, "", "==", "")
DDS_OPDEF(NOT_EQUAL_TO_OP_INT,            ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_LONG,           ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_LLONG,          ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_UINT,           ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_ULONG,          ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_ULLONG,         ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_FLOAT,          ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_DOUBLE,         ARG12XX, 2,  9, "", "!=", "")
   DDS_OPDEF(NOT_EQUAL_TO_OP_LDOUBLE,        ARG12XX, 2,  9, "", "!=", "")
DDS_OPDEF(BIT_AND_OP_INT,                 ARG12XX, 2,  8, "", "&", "")
   DDS_OPDEF(BIT_AND_OP_LONG,                ARG12XX, 2,  8, "", "&", "")
   DDS_OPDEF(BIT_AND_OP_LLONG,               ARG12XX, 2,  8, "", "&", "")
   DDS_OPDEF(BIT_AND_OP_UINT,                ARG12XX, 2,  8, "", "&", "")
   DDS_OPDEF(BIT_AND_OP_ULONG,               ARG12XX, 2,  8, "", "&", "")
   DDS_OPDEF(BIT_AND_OP_ULLONG,              ARG12XX, 2,  8, "", "&", "")
DDS_OPDEF(BIT_XOR_OP_INT,                 ARG12XX, 2,  7, "", "^", "")
   DDS_OPDEF(BIT_XOR_OP_LONG,                ARG12XX, 2,  7, "", "^", "")
   DDS_OPDEF(BIT_XOR_OP_LLONG,               ARG12XX, 2,  7, "", "^", "")
   DDS_OPDEF(BIT_XOR_OP_UINT,                ARG12XX, 2,  7, "", "^", "")
   DDS_OPDEF(BIT_XOR_OP_ULONG,               ARG12XX, 2,  7, "", "^", "")
   DDS_OPDEF(BIT_XOR_OP_ULLONG,              ARG12XX, 2,  7, "", "^", "")
DDS_OPDEF(BIT_OR_OP_INT,                  ARG12XX, 2,  6, "", "|", "")
   DDS_OPDEF(BIT_OR_OP_LONG,                 ARG12XX, 2,  6, "", "|", "")
   DDS_OPDEF(BIT_OR_OP_LLONG,                ARG12XX, 2,  6, "", "|", "")
   DDS_OPDEF(BIT_OR_OP_UINT,                 ARG12XX, 2,  6, "", "|", "")
   DDS_OPDEF(BIT_OR_OP_ULONG,                ARG12XX, 2,  6, "", "|", "")
   DDS_OPDEF(BIT_OR_OP_ULLONG,               ARG12XX, 2,  6, "", "|", "")
DDS_OPDEF(LOGICAL_AND_OP,                 ARGXXXX, 2,  5, "", "&&", "")
DDS_OPDEF(LOGICAL_OR_OP,                  ARGXXXX, 2,  4, "", "||", "")
DDS_OPDEF(CONDITIONAL_OP,                 ARG123X, 4,  3, "", " ? ", " : ")
DDS_OPDEF(COMMA_OP,                       ARGXXXX, 2,  1, "", ", ", "")
DDS_OPDEF(ERROR_OP,                       ARGXXXX, 0,  0, "", "", "")
DDS_OPDEF(NO_OP,                          ARGXXXX, 0,  0, "", "", "")

