/* dds_version.h - Part of DDS system: Wed Feb 19 07:33:08 CST 2020 */
/* This is automatically generated by the ddscode script in order*/
/* to force the current keyword values from the repository.        */
const char *dds_rcs_rev = "$Rev: 320 $";
const char *dds_rcs_date= "$Date: 2020-02-19 14:33:08 -0600 (Wed, 19 Feb 2020) $";
