##############################################
###   Copyright (C) 1997                   ###
###   AMOCO Corporation, Tulsa, OK 74102   ###
###   Randy Selzler, 25 Feb 1997           ###
##############################################
# $Id: Makefile 17 2009-01-06 22:26:44Z user $

include $(DDSROOT)/etc/MakeSrcMacro

include $(DDSROOT)/etc/MakeSrcRules

