
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;
extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[95] =
    {   0,
        0,    0,   34,   34,   40,   38,   36,   37,   38,   29,
       38,   38,   30,   38,   38,   38,   38,   38,   24,   24,
       38,   38,   28,   38,   38,   38,   34,   33,   39,   36,
        0,    0,   11,    0,    0,    3,    0,    4,    2,    0,
        0,   27,   32,    0,    0,   24,   27,   24,   24,    0,
        0,    5,    0,    6,    0,   28,   31,   13,    0,    0,
       12,   34,    0,   34,   35,   10,   16,   21,   14,   17,
       18,    1,    0,   15,   24,   26,   25,    0,    7,    0,
        8,    0,   22,   23,    0,   27,   26,   26,   25,   25,
       19,   20,    9,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   20,   21,
       22,   22,   22,   22,   22,   23,   22,   22,   22,   22,
       22,   22,   22,   22,   24,   22,   22,   25,   22,   22,
        1,   26,    1,   27,   22,    1,   19,   19,   19,   19,

       20,   21,   22,   22,   22,   22,   22,   23,   22,   22,
       22,   22,   22,   22,   22,   22,   24,   22,   22,   28,
       22,   22,    1,   29,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[30] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    1,    1,    3,    3,
        3,    4,    4,    4,    4,    1,    1,    4,    1
    } ;

static yyconst flex_int16_t yy_base[101] =
    {   0,
        0,    0,   27,   28,  131,  132,  128,  132,  103,  132,
      102,   25,  132,  101,   23,   24,   26,   30,   45,   18,
       18,   27,    0,   44,  100,   26,  116,  132,  111,  121,
      105,  104,  132,  103,  102,  132,  101,  132,  132,  100,
      104,   60,  132,   98,   48,    0,  132,  132,   91,    0,
        0,   87,   95,   85,   93,    0,  132,   81,   86,   77,
      132,   83,   78,   81,  132,  132,  132,  132,  132,  132,
      132,  132,   74,  132,  132,   41,   48,   65,  132,   62,
      132,   61,  132,  132,   62,   72,  132,   44,  132,   35,
      132,  132,  132,  132,   95,   97,  101,  105,   51,   45

    } ;

static yyconst flex_int16_t yy_def[101] =
    {   0,
       94,    1,   95,   95,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   19,
       94,   94,   96,   94,   94,   94,   97,   94,   98,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   20,   94,   94,   94,   99,
      100,   94,   94,   94,   94,   96,   94,   94,   94,   94,
       94,   97,   98,   97,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   99,  100,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,    0,   94,   94,   94,   94,   94,   94

    } ;

static yyconst flex_int16_t yy_nxt[162] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,    6,   22,   23,   23,
       23,   23,   23,   23,   23,   24,   25,   23,   26,   28,
       28,   33,   36,   52,   38,   29,   29,   41,   43,   42,
       42,   39,   94,   53,   54,   94,   57,   77,   37,   40,
       34,   60,   55,   76,   61,   44,   45,   89,   46,   46,
       58,   42,   42,   87,   88,   47,   87,   48,   49,   50,
       89,   90,   51,   42,   42,   86,   86,   93,   92,   73,
       47,   91,   47,   85,   85,   86,   86,   86,   86,   63,
       94,   63,   47,   84,   47,   27,   27,   27,   27,   56,

       56,   62,   83,   62,   62,   64,   82,   64,   64,   81,
       80,   79,   78,   75,   74,   72,   71,   70,   69,   68,
       67,   66,   30,   65,   63,   59,   35,   32,   31,   30,
       94,    5,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94
    } ;

static yyconst flex_int16_t yy_chk[162] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   12,   15,   21,   16,    3,    4,   17,   18,   17,
       17,   16,   20,   21,   22,   20,   24,  100,   15,   16,
       12,   26,   22,   99,   26,   18,   19,   90,   19,   19,
       24,   45,   45,   76,   76,   19,   88,   19,   19,   19,
       77,   77,   19,   42,   42,   85,   85,   82,   80,   42,
       42,   78,   42,   73,   73,   86,   86,   73,   73,   64,
       63,   62,   86,   60,   86,   95,   95,   95,   95,   96,

       96,   97,   59,   97,   97,   98,   58,   98,   98,   55,
       54,   53,   52,   49,   44,   41,   40,   37,   35,   34,
       32,   31,   30,   29,   27,   25,   14,   11,    9,    7,
        5,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[39] =
    {   0,
      149,  150,  151,  152,  153,  154,  155,  156,  157,  158,
      159,  160,  161,  162,  163,  164,  165,  166,  167,  168,
      169,  170,  171,  174,  175,  176,  252,  289,  359,  426,
      508,  513,  517,  519,  521,  525,  529,  535
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
/*************************************************/
/***   "definitions" 1st section of scanner.   ***/
/*************************************************/
/*
RCS-t=DDS, GNU flex scanner for binary format and map definitions.

*/

/**********************************************/
/***   Copyright (C) 1996                   ***/
/***   AMOCO Corporation, Tulsa, OK 74102   ***/
/***   Randy Selzler, xx May 1996           ***/
/**********************************************/

   #include <limits.h>
   #include "dds_sys.h"
   #include "parser.tab.h"

   #undef YY_INPUT
   #define YY_INPUT(buf, size, max) \
      ((size) = ddsYYinput((char*)(buf), (max)))

   #define DEFN_NEST_MAX 10

   /* length of character string (used with STRING_TOKEN) */
   static size_t str_size;

   #define YY_SKIP_YYWRAP
   #undef yywrap
   static int yywrap(void);

   static size_t ddsYYinput(char *buf, size_t max);

   static DDS_OBJECT * ddsYYdepend(const char *name);

   /* Push scanner stack (nested input) */
   #define SCANNER_PUSH(LEOF, DICT, DEFN, START, STOP, LINE)  \
      dds_lexer->yy_buf = YY_CURRENT_BUFFER;  \
      dds_lexer->leof = LEOF;  \
      dds_lexer->dict = (DICT);  \
      dds_lexer->defn = (DEFN);  \
      if(dds_lexer->inner) {  \
         dds_lexer = dds_lexer->inner;  \
      } else {  \
         dds_lexer->inner = ddsZalloc(sizeof(DDS_SCANNER));  \
         dds_lexer->inner->outer = dds_lexer;  \
         dds_lexer = dds_lexer->inner;  \
      }  \
      dds_lexer->leof = DDS_FALSE;  \
      dds_lexer->dict = NULL;  \
      dds_lexer->defn = NULL;  \
      dds_lexer->start = (START);  \
      dds_lexer->next = (START);  \
      dds_lexer->stop = (STOP);  \
      dds_lexer->line = (LINE);  \
      yy_buf = yy_create_buffer(NULL,YY_BUF_SIZE);  \
      yy_switch_to_buffer(yy_buf);

   /* Pop scanner stack (compliment of PUSH) */
   #define SCANNER_POP  \
      if(dds_lexer->defn) ddsFree((void*)dds_lexer->defn);  \
      yy_delete_buffer(YY_CURRENT_BUFFER);  \
      dds_lexer = dds_lexer->outer;  \
      yy_switch_to_buffer(dds_lexer->yy_buf);

   DDS_SCANNER *dds_lexer = NULL;
   DDS_SCANNER dds_lexer_root = {NULL};

   /*** extern YYSTYPE dds_yylval; ***/
   /*** #define yylval(member)  dds_yylval.member ***/

   /* following required for bison "pure" parsers */
   #undef  YY_DECL
   #define YY_DECL   int ddsYYlex(YYSTYPE *lvalp)
   #define yylval(member) lvalp->member

#define INITIAL 0
#define X_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "io.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#if defined(_WIN32) || defined(MINGW)
#include <io.h>
#else
#include <unistd.h>
#endif
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %if-bison-bridge */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */

   /*******************************************/
   /***   "rules" 2nd section of scanner.   ***/
   /*******************************************/

   #undef YY_BREAK
   #define YY_BREAK

   DDS_KEYWORD *key;
   DDS_OBJECT *object;
   DDS_VALUE *value;
   DDS_PTYPE ptype;

   const char *name, *name_ptr;
   char *end_ptr;
   size_t size;
   void *value_ptr, *text_ptr;
   int char_in, char_const, char_value;
   int parse_rc;
   int comment_state;
   unsigned long ul_con;        /* unsigned long integer constant */
   double d_con;                /* double constant */

   /* propagate debug trace flag */
   yy_flex_debug = dds_yy_flex_debug;

   /* process lex start state and its changes */
   switch(dds_lex_ss) {
   case DDS_LEX_CONTINUE:
      break;
   case DDS_LEX_SHARED:
      dds_lex_ss = DDS_LEX_CONTINUE;
      BEGIN(INITIAL);
      break;
   case DDS_LEX_TRANSLATE:
      dds_lex_ss = DDS_LEX_CONTINUE;
      BEGIN(INITIAL);
      yylval(YYvoid) = 0;
      return TRANSLATION_UNIT;
   case DDS_LEX_IDENT:
      dds_lex_ss = DDS_LEX_CONTINUE;
      BEGIN(INITIAL);
      yylval(YYvoid) = 0;
      return IDENT_UNIT;
   case DDS_LEX_DEFN:
      dds_lex_ss = DDS_LEX_CONTINUE;
      BEGIN(INITIAL);
      yylval(YYvoid) = 0;
      return DEFN_UNIT;
   case DDS_LEX_MAP:
      dds_lex_ss = DDS_LEX_CONTINUE;
      BEGIN(INITIAL);
      yylval(YYvoid) = 0;
      return MAP_EXPR;
   default:
      ddsPanic("dds_yylex: bad dds_lex_ss\n");
   }

   /* end of preprocessing */
   /* empty */

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 95 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 132 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 39 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 39 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 40 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return ELIPSE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return STRUCT_POINTER_OP;}
	YY_BREAK
case 3:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return INCREMENT_OP;}
	YY_BREAK
case 4:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return DECREMENT_OP;}
	YY_BREAK
case 5:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return LEFT_SHIFT_OP;}
	YY_BREAK
case 6:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return RIGHT_SHIFT_OP;}
	YY_BREAK
case 7:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return LESS_EQUAL_OP;}
	YY_BREAK
case 8:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return GREATER_EQUAL_OP;}
	YY_BREAK
case 9:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return EQUAL_TO_OP;}
	YY_BREAK
case 10:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return NOT_EQUAL_TO_OP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return LOGICAL_AND_OP;}
	YY_BREAK
case 12:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return LOGICAL_OR_OP;}
	YY_BREAK
case 13:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return ASSIGN_OP;}
	YY_BREAK
case 14:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return MULTIPLY_ASSIGN_OP;}
	YY_BREAK
case 15:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return DIVIDE_ASSIGN_OP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return MODULO_ASSIGN_OP;}
	YY_BREAK
case 17:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return PLUS_ASSIGN_OP;}
	YY_BREAK
case 18:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return MINUS_ASSIGN_OP;}
	YY_BREAK
case 19:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return LEFT_SHIFT_ASSIGN_OP;}
	YY_BREAK
case 20:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return RIGHT_SHIFT_ASSIGN_OP;}
	YY_BREAK
case 21:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return BIT_AND_ASSIGN_OP;}
	YY_BREAK
case 22:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return BIT_XOR_ASSIGN_OP;}
	YY_BREAK
case 23:
YY_RULE_SETUP
{yylval(YYvoid) = 0; return BIT_OR_ASSIGN_OP;}
	YY_BREAK
case 24:
case 25:
case 26:
YY_RULE_SETUP
{
      /* integral constant */
      errno = 0;
      ul_con = strtoul(yytext, &end_ptr, (int)0);
      if(errno) ddsYYError("'%s' overflows type 'unsigned long int'\n", yytext);
      size = strlen(yytext);
      if(! strchr("uUlL", yytext[size - 1])) {
         /* unsuffixed */
         if(yytext[0] == '0') {
            /* octal or hexadecimal */
            if(ul_con <= INT_MAX) {
               ptype = DDS_CTYPE_INT;
            } else if(ul_con <= UINT_MAX) {
               ptype = DDS_CTYPE_UINT;
            } else if(ul_con <= LONG_MAX) {
               ptype = DDS_CTYPE_LONG;
            } else {
               ptype = DDS_CTYPE_ULONG;
            }
         } else {
            /* decimal */
            if(ul_con <= INT_MAX) {
               ptype = DDS_CTYPE_INT;
            } else if(ul_con <= LONG_MAX) {
               ptype = DDS_CTYPE_LONG;
            } else {
               ptype = DDS_CTYPE_ULONG;
            }
         }
      } else if(strchr("uU", yytext[size - 1]) ||
         strchr("uU", yytext[size - 2])) {
         /* unsigned */
         if(ul_con <= UINT_MAX &&
            ! (strchr("lL", yytext[size - 1]) ||
            strchr("lL", yytext[size - 2]))) {
            ptype = DDS_CTYPE_UINT;
         } else {
            ptype = DDS_CTYPE_ULONG;
         }
      } else if(strchr("lL", yytext[size - 1]) ||
         strchr("lL", yytext[size - 2])) {
         /* long */
         if(ul_con <= LONG_MAX) {
            ptype = DDS_CTYPE_LONG;
         } else {
            ptype = DDS_CTYPE_ULONG;
         }
      }

      value_ptr = ddsTablePush(dds_symbol, dds_prime[ptype].prec,
         dds_prime[ptype].align);
      name_ptr = ddsTablePushStr(dds_symbol, yytext);
      value = ddsSymObjectLit(name_ptr, (DDS_SYM_FLAG)DDS_SYM_PREP,
         dds_prime[ptype].type, value_ptr, 0);

      switch(ptype) {
      case DDS_CTYPE_INT:
         *(int*)(value_ptr) = ul_con;
         break;
      case DDS_CTYPE_UINT:
         *(unsigned*)(value_ptr) = ul_con;
         break;
      case DDS_CTYPE_LONG:
         *(long*)(value_ptr) = ul_con;
         break;
      case DDS_CTYPE_ULONG:
         *(unsigned long*)(value_ptr) = ul_con;
         break;
      default:
         ddsPanic("scanner.l: integral constant, bad ptype\n");
      }
      yylval(YYvalue) = value;
      return INTEGER_TOKEN;
   }
	YY_BREAK
case 27:
YY_RULE_SETUP
{
      /* floating point token */
      errno = 0;
      d_con = strtod(yytext, &end_ptr);
      size = strlen(yytext);
      if(! strchr("fF", yytext[size - 1])) {
         ptype = DDS_CTYPE_FLOAT;
      } else if(! strchr("lL", yytext[size - 1])) {
         ptype = DDS_CTYPE_LDOUBLE;
      } else {
         ptype = DDS_CTYPE_DOUBLE;
      }
 
      value_ptr = ddsTablePush(dds_symbol,
         dds_prime[ptype].prec, dds_prime[ptype].align);
      name_ptr = ddsTablePushStr(dds_symbol, yytext);
      value = ddsSymObjectLit(name_ptr, (DDS_SYM_FLAG)DDS_SYM_PREP,
         dds_prime[ptype].type, value_ptr, 0);

      switch(ptype) {
      case DDS_CTYPE_FLOAT:
         *(float*)(value_ptr) = d_con;
         break;
      case DDS_CTYPE_DOUBLE:
         *(double*)(value_ptr) = d_con;
         break;
      case DDS_CTYPE_LDOUBLE:
         *(HOST_LDOUBLE_T*)(value_ptr) = d_con;
         break;
      default:
         ddsPanic("scanner.l: float constant, bad ptype\n");
      }
      yylval(YYvalue) = value;
      return FLOATING_TOKEN;
   }
	YY_BREAK
case 28:
YY_RULE_SETUP
{
      /* "name" found (keyword, TYPEDEF_TOKEN,  */
      /*    ENUMERATION_TOKEN, or IDENTIFIER_TOKEN) */
      key = (DDS_KEYWORD*)ddsTableLookup(&dds_keyword, yytext);
      if(key) {
         /* name is a keyword */
         if(key->token == IDENT) {
            /* prognosis: ident("SHOT-X"), or other funky name */
            /* Support for arbitrary identifier names. */
            dds_lex_ss = DDS_LEX_IDENT;
            if(dds_yy_flex_debug) fprintf(stderr, "==ddsYYlex: parse ident(\"...\")\n");
            parse_rc = ddsYYparse(&value);
            if(dds_yy_flex_debug) fprintf(stderr, "##ddsYYlex: parse ident(\"...\")\n");
            if(parse_rc) {
               /* parse error */
               name = ddsTablePushStr(dds_symbol, "ident(<bad>)");
            } else {
               name = value->ptr;
            }
            /* fall through and process like an identifier */
         } else if(key->token == DEFN_VALUE) {
            /* prognosis: defn_value("dict_name","defn_alias") */
            /* Support for nested input from defn and dict. */
            dds_lex_ss = DDS_LEX_DEFN;
            if(dds_yy_flex_debug) fprintf(stderr, "==ddsYYlex: parse ident(\"...\")\n");
            parse_rc = ddsYYparse(NULL);
            if(dds_yy_flex_debug) fprintf(stderr, "##ddsYYlex: parse ident(\"...\")\n");
            break; /* continue scanning more tokens */
         } else {
            /* prognosis: reserved keyword in grammer. */
            yylval(YYvoid) = 0;
            return key->token; /* token associated with keyword */
         }
      } else {
         /* push "name/identifier" onto table */
         name = ddsTablePushStr(dds_symbol, yytext);
      }

      if(! (dds_declare->flag & DDS_SYM_IDENT)) {
         /* The parser does NOT want an IDENTIFIER_TOKEN, i.e. */
         /* its not expecting a tag name or declarator for a type. */
         object = LOOKUP_OBJECT_NEW(dds_symbol, name, dds_block);

         if(! dds_map_value && ! object) {
            /* We are NOT compiling an rvalue for a map expression */
            /* and this "name/identifier" is NOT a defined object. */
            /* A syntax error is pending, unless ddsYYdepend */
            /* can compile an object into the symbol table. */
            object = ddsYYdepend(name);
         }

         if(object) {
            /* "name" identifier is declared */
            if(object->flag & DDS_SYM_TYPEDEF) {
               /* Use existing typdef (don't declare new one). */
               yylval(YYtype) = ddsSymTypeMerge(object->type);
               yylval(YYtype)->trail = object;
               return TYPEDEF_TOKEN;
            } else if(object->flag & DDS_SYM_ENUM) {
               /* use existing object (enumerated constant) */
               yylval(YYvalue) = (DDS_VALUE*)object;
               return ENUMERATION_TOKEN;
            }
         }
      }
      yylval(YYname) = name;
      return IDENTIFIER_TOKEN;
   }
	YY_BREAK
case 29:
YY_RULE_SETUP
{
      /* Opening double quote.   Scan the string constant and */
      /* save it in the symbol table. */
      value_ptr = dds_symbol->page.ptr + dds_symbol->page.top;

      /* consume all characters in all adjacent strings. */
      while(DDS_TRUE) {
         char_in = input();
         while(char_in == '"') {
            /* closing double quote */
            do {char_in = input();}
               while(char_in != EOF &&
                  isspace(char_in)); /* eat white space */

            if(char_in == '"') {
               /* opening quote for adjacent string, concantenate. */
               char_in = input();
            } else {
               /* next token is not a string. */
               unput(char_in);
               goto string_done;
            }
         }
         if(char_in == '\\') {
            /* decode string escape sequence '\t', '\n', etc. */
            char_in = input();
            switch(char_in) {
            case '\n':
               /* line splicing (eat '\\' and '\n') */
               dds_lexer->line++;
               continue;
            case '\\': char_in = '\\'; break;
            case  'n': char_in = '\n'; break;
            case  't': char_in = '\t'; break;
            case  'v': char_in = '\v'; break;
            case  'b': char_in = '\b'; break;
            case  'r': char_in = '\r'; break;
            case  'f': char_in = '\f'; break;
            /* silence warnings from Sun acc regarding '\a' usage */
            case  'a': char_in = DDS_ASCII_ALERT; break;
            }
         } else if(char_in == '\n') {
            ddsYYError("newline within string constant\n");
            dds_lexer->line++;
            break;
         } else if(char_in == EOF) {
            ddsYYError("EOF within string constant\n");
            break;
         }

         /* append another character to string */
         value_ptr = (void*)ddsTablePushChar(dds_symbol, value_ptr, char_in);
      }

      /* closing quote found (or syntax error detected). */
      string_done:
      str_size = dds_symbol->page.top -
         ((char*)value_ptr - dds_symbol->page.ptr);
      value_ptr = (void*)ddsTablePushChar(dds_symbol, value_ptr, '\0');

      value = ddsSymObjectLit(value_ptr, (DDS_SYM_FLAG)DDS_SYM_PREP,
         dds_prime[DDS_CTYPE_CHAR].type, value_ptr, str_size);
      yylval(YYvalue) = value;
      return STRING_TOKEN;
   }
	YY_BREAK
case 30:
YY_RULE_SETUP
{
      /* Opening single quote.   Scan the character constant and */
      /* save it in the symbol table. */
      text_ptr = dds_symbol->page.ptr + dds_symbol->page.top;
      text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, '\'');
      char_const = 0;

      /* consume all characters in the constant. */
      for(char_in = input();
         char_in != '\'' && char_in != EOF;
         char_in = input()) {
         text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, char_in);
         /* translate escape sequences */
         if(char_in == '\\') {
            /* decode escape sequence '\ooo', '\xhh', '\t', '\n', etc. */
            char_in = input();
            text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, char_in);
            switch(char_in) {
            case '0': case '1': case '2': case '3':
            case '4': case '5': case '6': case '7':
               /* octal sequence of 1, 2, or 3 characters. */
               char_value = char_in - '0';
               char_in = input();
               text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, char_in);
               if(char_in >= '0' && char_in <= '7') {
                  char_value = (char_value << 3) + char_in - '0';
                  char_in = input();
                  text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, char_in);
                  if(char_in >= '0' && char_value <= '7') {
                     char_value = (char_value << 3) + char_in - '0';
                  } else {
                     unput(char_in);
                  }
               } else {
                  unput(char_in);
               }
               break;
            case 'x': case 'X':
               /* hexidecimal sequence of N characters. */
               char_value = 0;
               while(DDS_TRUE) {
                  char_in = input();
                  text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, char_in);
                  if(char_in >= '0' && char_in <= '9') {
                     char_value = (char_value << 4) + char_in - '0';
                  } else if(char_in >= 'a' && char_in <= 'f') {
                     char_value = (char_value << 4) + 10 + char_in - 'a';
                  } else if(char_in >= 'A' && char_in <= 'F') {
                     char_value = (char_value << 4) + 10 + char_in - 'A';
                  } else {
                     break;
                  }
               }
               unput(char_in);
               break;
            case '\\': char_value = '\\'; break;
            case  'n': char_value = '\n'; break;
            case  't': char_value = '\t'; break;
            case  'v': char_value = '\v'; break;
            case  'b': char_value = '\b'; break;
            case  'r': char_value = '\r'; break;
            case  'f': char_value = '\f'; break;
            /* silence warnings from Sun acc regarding '\a' usage */
            case  'a': char_value = DDS_ASCII_ALERT; break;
            }
         } else {
            char_value = char_in;
         }
         /* accumulate another character into the constant */
         char_const = (char_const << CHAR_BIT) + char_value;
      }
      text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, '\'');
      text_ptr = (void*)ddsTablePushChar(dds_symbol, text_ptr, '\0');
      value_ptr = ddsTablePush(dds_symbol, HOST_INT_P, HOST_INT_A);
      *(int*)value_ptr= char_const;
      value = ddsSymObjectLit(text_ptr, (DDS_SYM_FLAG)DDS_SYM_PREP,
         dds_prime[DDS_CTYPE_INT].type, value_ptr, 0);
      yylval(YYvalue) = value;
      return CHARACTER_TOKEN;
   }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
{
      /* BROKEN, if splice should join token pieces ? */
      /* line splicing, count newline*/ dds_lexer->line++; break;}
	YY_BREAK
case 32:
YY_RULE_SETUP
{
      /* begin comment */ comment_state = YYSTATE; BEGIN(X_COMMENT); break;}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
{
      /* count newline in comment */ dds_lexer->line++; break;}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
      /* discard comment text */ break;}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
      /* terminate comment */ BEGIN(comment_state); break;}
	YY_BREAK
case 36:
YY_RULE_SETUP
{
      break; /* ignore white space */ }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
{
      /* newline processing. */
      dds_lexer->line++;
      break;}
	YY_BREAK
case 38:
YY_RULE_SETUP
{
      /* all other characters, return their pristene value */
      yylval(YYvoid) = 0;
      return *yytext;}
	YY_BREAK
case 39:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(X_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 95 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 95 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 94);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

   /***********************************************/
   /***   "user code" 3rd section of scanner.   ***/
   /***********************************************/

void ddsLexStr(
   DDS_BOOLEAN leof,
   const char *dict,
   const char *defn,
   const char *start,
   const char *stop,
   size_t line)
{
   YY_BUFFER_STATE yy_buf;
   int size;

   /* If "leof" is DDS_TRUE, this input is NOT nested, */
   /* i.e. scanner returns EOF when this string is consumed. */
   /* If "leof" is DDS_FALSE, this input IS nested, */
   /* i.e. scanner continues processing previous string */
   /* after this string has been consumed. */

   if(dds_yy_flex_debug) {
      size = stop - start;
      if(size < 100)
         fprintf(stderr, "==ddsLexStr: input '%.*s'\n",   size, start);
      else
         fprintf(stderr, "==ddsLexStr: input '%.*s...'\n", 100, start);
   }

   SCANNER_PUSH(leof, dict, defn, start, stop, line);

   return;
}

static int yywrap(void)
{  /* scanner input "eof" processing */

   if(dds_lexer == &dds_lexer_root) {
      ddsPanic("yywrap: multiple calls\n");
      return 1;
   }

   SCANNER_POP;

   if(dds_lexer->leof) return 1; /* EOF on buffer chain */

   return 0;
}

static size_t ddsYYinput(
   char *buf, 
   size_t max)
{  /* lex input from string (setup by ddsLexStr) */
   size_t size;

   size = dds_lexer->stop - dds_lexer->next;

   if(max < size) size = max;

   memcpy(buf, dds_lexer->next, size);

   dds_lexer->next += size;
   
   return size ? size : YY_NULL;
}

void ddsDefnValue(
   DDS_VALUE *dict_value,
   DDS_VALUE *defn_value)
{  /* nested input from another definitions */
   const char *dict, *defn;

   dict = dict_value->ptr;
   defn = ddsString(defn_value->ptr);

   if(! cdds_dict(dict, "scan") && ! cdds_scanf(defn, "")) {
      ddsLexStr(DDS_FALSE,
         dict, defn, dds_scan_token.next,
         dds_scan_dict->buf.ptr + dds_scan_newer->start,
         dds_scan_defn->line);
   } else {
      ddsVerbose("not found 'defn_value(\"%s\",\"%s\")'\n",
         dict, defn);
   }
   return;
}

#define ALIAS_MAX 1024

static DDS_OBJECT * ddsYYdepend(
   const char *name)
{
   static DDS_STRING alias = NULL_STRING;
   DDS_STATE create_state;
   DDS_LEX_START save_lex_ss;
   DDS_BLOCK *save_block;
   DDS_SYM *save_newest, *save_newer;
   DDS_SCANNER *scan;
   DDS_OBJECT *object;
   const char *dict, *defn;
   int level;

   /**************************************************************/
   /* Parse definitions to declare struct/union dependencies.    */
   /*                                                            */
   /* This processing deviates from the nominal "C" model.       */
   /* "C" requires all symbols to be declared before use.        */
   /* "#include" explicitly references all input "C" source.     */
   /*                                                            */
   /* In DDS, declarations are scattered among many definitions. */
   /* Dictionary definitions are implicitly referenced, i.e. if  */
   /* an identifier is referenced that is not already declared,  */
   /* an attempt is made to find and compile the required defn.  */
   /**************************************************************/

   cdds_dict(dds_compile->dict_fmt, "scan");
   create_state = (DDS_STATE)(dds_state & DDS_YACC_CREATE);
   save_block = dds_block;

   if(dds_state & DDS_YACC_CREATE) {
      /* Compile format using "new" precedence. */
      /* Try format rule to CREATE new symbols (fmt:-:-.name). */
      ddsAliasName3(&alias, "fmt", dds_compile->old_format, 
         dds_compile->alias_name, name);
      if(cdds_scanf(alias.ptr, "")) {
         ddsAliasName3(&alias, "fmt", dds_compile->old_format,
            dds_compile->fmt_name, name);
         if(cdds_scanf(alias.ptr, "")) {
            /* "CREATE rule" is not defined. */
            /* Expand symbol table search into block_old. */
            object = LOOKUP_OBJECT(dds_symbol, name, dds_block);
            if(object) {
               /* Object is defined within block_old.  Use it ! */
               return object;
            } else {
               /* Try format rule for EXISTING symbols (fmt:-.name). */
               ddsStrCpyCat2(&alias, "fmt:", name);
               if(cdds_scanf(alias.ptr, "")) {
                  /* "EXISTING rule" is not defined. */
                  /* Fail! parser will have an undefined symbol error */
                  return NULL;
               }
               /* re-open the block_old scope */
               dds_block = dds_compile->block_old;
               dds_state &= (DDS_STATE) ~ DDS_YACC_CREATE;
            }
         } else {
            /* re-open the block_new scope */
            dds_block = dds_compile->block_new;
         }
      } else {
         /* re-open the block_new scope */
         dds_block = dds_compile->block_new;
      }
   } else {
      /* Compile format using "old" precedence. */
      /* Try format rule for EXISTING symbols (fmt:-.name). */
      ddsStrCpyCat2(&alias, "fmt:", name);
      if(cdds_scanf(alias.ptr, "")) {
         /* "EXISTING rule" is not defined. */
         /* Try format rule to CREATE new symbols (fmt:-:-.name). */
         ddsAliasName3(&alias, "fmt", dds_compile->old_format,
            dds_compile->alias_name, name);
         if(cdds_scanf(alias.ptr, "")) {
            ddsAliasName3(&alias, "fmt", dds_compile->old_format,
               dds_compile->fmt_name, name);
            if(cdds_scanf(alias.ptr, "")) {
               /* "CREATE rule" is not defined. */
               /* Fail ! parser will have an undefined symbol error */
               return NULL;
            }
         }
      }
      if(dds_compile->state & DDS_BIN_OPEN_CREATE) {
         /* re-open the block_old scope */
         dds_block = dds_compile->block_old;
      } else {
         /* re-open the block_new scope */
         dds_block = dds_compile->block_new;
      }
   }

   /*****************************************************************/
   /* Call ddsYYparser recursively, which should create the object. */
   /*****************************************************************/

   for(scan = dds_lexer, level = DEFN_NEST_MAX;
      scan && level;
      scan = scan->outer, level--) /* empty */ ;

   if(scan) {
      ddsError("binary format definition nesting > %i\n\tdict= %s, defn=%s\n\tbinary= %s\n",
         DEFN_NEST_MAX, dds_scan_dict->name,
         dds_scan_name, dds_compile->name);
      return NULL;
   }

   dict = dds_scan_dict->name;
   defn = ddsString(dds_scan_name);

   /* preserve current state */
   save_lex_ss = dds_lex_ss;
   DECLARE_INNER;
   save_newest = (DDS_SYM*)dds_symbol->newest;
   save_newer = (DDS_SYM*)dds_block->newer;

   /* disconnect the older/newer symbol chain. */
   dds_symbol->newest = (DDS_ITEM*)dds_block;
   dds_block->newer = NULL;
   if(save_newer) save_newer->older = NULL;

   /* initialize flags, blocks, and lex input */
   dds_lex_ss = DDS_LEX_TRANSLATE;

   /* tell the scanner where to find the input text */
   ddsLexStr(DDS_TRUE, dict, defn, dds_scan_token.next,
      dds_scan_dict->buf.ptr + dds_scan_newer->start,
      dds_scan_defn->line);

   if(dds_yy_flex_debug) fprintf(stderr,
      "==ddsYYdepend: parse dependency '%s'\n", defn);

   /* compile format definitions for binary data */
   ddsYYparse(NULL);

   if(dds_yy_flex_debug) fprintf(stderr,
      "##ddsYYdepend: parse dependency '%s'\n", defn);

   object = LOOKUP_OBJECT(dds_symbol, name, dds_block);

   if(save_newer) {
      /* reconnect the symbol chain */
      save_newer->older = (DDS_ITEM*)dds_symbol->newest;
      dds_symbol->newest->newer = (DDS_ITEM*)save_newer;
      dds_symbol->newest = (DDS_ITEM*)save_newest;
   }

   DECLARE_OUTER;
   dds_lex_ss = save_lex_ss;
   dds_block = save_block;
   dds_state |= create_state;

   return object;
}

int ddsYYerror(
   const char *msg)
{
   /* Only called by "bison", when it detects a syntax error. */
   /* It should NOT be called by any DDS functions directly. */
   return ddsYYError("%s%s", msg, "\n");
}

int ddsYYError(
   const char *fmt,
   ...)
{
   DDS_BOOLEAN print_msg;
   const char *dict_name, *defn_name;
   int n, line_numb;
   char msg[DDS_MSG_MAX+1];
   va_list args;
 
   va_start(args, fmt);

   if(dds_state & (DDS_VERBOSE | DDS_ERROR_ABORT | DDS_ERROR_PRINT)) {
      print_msg = DDS_TRUE;
   } else {
      print_msg = DDS_FALSE;
   }

   dds_error_count++;

   if(dds_lexer->outer) {
      dict_name = dds_lexer->outer->dict;
      defn_name = dds_lexer->outer->defn;
      line_numb = dds_lexer->line;
   } else {
      dict_name = dds_compile->dict_open;
      defn_name = "<defn_name>";
      line_numb = 0;
   }
 
   sprintf(msg, "DDS SYNTAX ERROR: dict=%s, line= %i, defn= %s\n\t",
      dict_name, line_numb, defn_name);

   /* Message body supplied by caller. */
   /* Intermediate lines terminated by "\n\t", last line by "\n". */
   n = strlen(msg);
   vsprintf(msg + n, fmt, args);
   va_end(args);
   if(print_msg) ddsPrintStr(msg);
   ddsStrCpy(&dds_error_msg, msg);

   return errno ? errno : (dds_error ? dds_error : EINVAL) ;
}

int ddsYYWarn(
   const char *fmt,
   ...)
{
   DDS_BOOLEAN print_msg;
   const char *dict_name, *defn_name;
   int n, line_numb;
   char msg[DDS_MSG_MAX+1];
   va_list args;
 
   va_start(args, fmt);

   if(dds_state & (DDS_VERBOSE | DDS_WARN_ABORT | DDS_WARN_PRINT)) {
      print_msg = DDS_TRUE;
   } else {
      print_msg = DDS_FALSE;
   }

   dds_warn_count++;
 
   if(dds_lexer->outer) {
      dict_name = dds_lexer->outer->dict;
      defn_name = dds_lexer->outer->defn;
      line_numb = dds_lexer->line;
   } else {
      dict_name = dds_compile->dict_open;
      defn_name = "<defn_name>";
      line_numb = 0;
   }
 
   sprintf(msg, "DDS SYNTAX WARNING: dict=%s, line= %i, defn= %s\n\t",
      dict_name, line_numb, defn_name);

   /* Message body supplied by caller. */
   /* Intermediate lines terminated by "\n\t", last line by "\n". */
   n = strlen(msg);
   vsprintf(msg + n, fmt, args);
   va_end(args);
   if(print_msg) ddsPrintStr(msg);
   ddsStrCpy(&dds_warn_msg, msg);

   return errno ? errno : (dds_error ? dds_error : EINVAL) ;
}

#include "dds_dump.h"

void ddsDumpScanner(
   void *handle)
{
   DDS_SCANNER *scan = handle;

   if(! dds_initialized) return; /* no-op */

   if(! scan) {
      fprintf(dds_print_fp, "ddsDumpScanner: NULL SCAN ptr\n");
      return;
   }

   if(scan->outer) {
      ddsDumpScanner(scan->outer);
   }

   fprintf(dds_print_fp, "SCANNER &= %p; ", (void*)scan);
   if(! scan->outer)
      fprintf(dds_print_fp, "OLDEST ");
   else
      fprintf(dds_print_fp, "NEWER ");
   fprintf(dds_print_fp, "leof= %s; line= %i;\n",
      scan->leof ? "TRUE" : "FALSE",
      (int)scan->line);
   fprintf(dds_print_fp, "%*sdict= %s; defn= %s;\n",
      DDS_DENT, "", scan->dict ? scan->dict : "<nil>",
                    scan->defn ? scan->defn : "<nil>");
   fprintf(dds_print_fp, "%*sstart= %.*s...\n",
      DDS_DENT, "", 50, scan->start ? scan->start : "<nil>");
   fprintf(dds_print_fp, "%*snext= %.*s...\n",
      DDS_DENT, "", 50, scan->next ? scan->next : "<nil>");

   return;
}

