#!/bin/sh

USER_MAIL=/tmp/DistMail.$$

trap "rm -f ${USER_MAIL}" 0

help="false"
prev=
newargs=
for arg do
   case $arg in
      to=*)
	eval $arg;;
      body=*)
	eval $arg;;
      subj=*) 
	eval $arg;;
      file=*) 
	eval $arg;;
      help=*)
        help="true";;
      *=*) 
	newargs="${newargs} ${prev}";;
      *) case $prev in
            to=*)
		to="${to:+$to }$arg";
		arg="${prev}";;
            body=*)
		body="${body:+$body }$arg";
		arg="${prev}";;
            subj=*)
		subj="${subj:+$subj }$arg";
		arg="${prev}";;
            file=*)
		file="$file$arg ";
		arg="${prev}";;
            *)
                newargs="${newargs} ${prev}";;
         esac
   esac
   prev=$arg
done

if [ "$help" = "true" ]; then
  command=`basename $0`
  echo Usage: $command "to= [addresses] [ body= text ] [subj = subject_text] [file= mailfile]"
  exit 0
fi

test -f ${USER_MAIL} && rm -f ${USER_MAIL}
cat > ${USER_MAIL} << EOF1
HELO localhost
MAIL FROM: ${USER}@localhost
EOF1

for addr in $to
do
echo "RCPT TO: ${addr}" >> ${USER_MAIL}
done

cat >> ${USER_MAIL} << EOF2
DATA
To: ${to}
Subject: ${subj}
EOF2

if [ "${file}" != "" ]; then
  if [ -f ${file} ]; then
    cat ${file} >> ${USER_MAIL}
  else
    echo Error in $0: File $file 'specified via file= not found'
    exit 1
  fi
elif [ "${body}" != "" ]; then
  echo "${body}" >> ${USER_MAIL}
else
  read line
  while [ $? -eq 0 ]; do
    echo $line >> ${USER_MAIL}
    read line
  done
fi

echo '.' >> ${USER_MAIL}

/hpc/tstapps/asi/src/dds/bin/dds-mailer.cgi < ${USER_MAIL}

exit 0
