#!/bin/sh

knt=1

for x in `ldd ${EXEC_APP} | grep 'not[ ]*found' | awk '{print $1}'`
do
  if [ $knt -eq 1 ]; then
   echo ' '
   echo "Checking shareable libraries required for binary"
   echo  "  $EXEC_APP"
   echo ' '
   echo 'These libaries could not be resolved:'
   knt=2
  fi
  echo '    ' $x
done

if [ ${knt} -ne 1 ]; then
  echo ' '
  echo  For submitting a bug report, please refer to the FreeDDS user group
  echo ' '
  exit 1
fi
