#!/bin/sh
###############################################################
#                 copyright 2010, BP America Inc.             #
#                       All Rights Reserved                   #
###############################################################
#
# DDS script to setup Landmark environment
#
# set -x

help=no
for arg do
   case $arg in
      -h|-?|help=*|HELP=*|Help=*|-help=*|-HELP=*|-Help=*) help=yes;;
   esac
done

if [ -n "${OWHOME}" ]; then
  if [ -f ${OWHOME}/revisions/OpenWorks ]; then
    export OWVERSION=`tail -1 $OWHOME/revisions/OpenWorks | awk '{print $2}' | awk -F. '{print $1}'`
    export CAE_SITE="/gad/local/r5k"
  fi
fi 

# this is the case where we are not in a CAE xterm

if [ $help = "no" -a -z "${OWHOME}" ]; then

   OWHOME=/local/tmp/${USER}
#
# Try to set up the landmark environment
#
   eval DISTRICT=`ddsarg arg=district default=NOTSET $*`
   if [ "$DISTRICT" == "NOTSET" ]; then
      echo "ERROR: need to either set the district= parameter or have the landmark environment already setup!"
      echo "       if you are attempting to run R5000 processing, please be aware that porting of the DDS"
      echo "       tools for this environment is not yet complete. "
      exit -1
   fi

   . /gad/local/scripts/R5000/OpenWorks/lgcprofile > /dev/null 2>&1

   export OW_DEFAULT_DISRICT=$DISTRICT
   export OW_CONF_DIR=/gad/local/r5k/conf

   if [ `awk '{if($1==district) print $2 }' district=$DISTRICT ${OW_CONF_DIR}/district.dat | wc -l` == 0 ]; then
      echo "ERROR: cannot find district=$DISTRICT!"
      exit -1
   fi

   export OWSYSSID=`awk '{if($1==district) print $4 }' district=$DISTRICT ${OW_CONF_DIR}/district.dat`
   export OW_HOME_DIR=${HOME}/R5K
   export OW_DDF=/local/${USER}/Landmark/conf/${DISTRICT}.dir.dat
   export ORACLE_SID=$OWSYSSID
   export WOW_ALLOW_LIST=1
   export OWVERSION=5000
fi
