static char rcsid[]="$Id: makehost.c 162 2010-07-28 21:04:20Z user $";
/*
RCS-t=DDS main, make host.h 

*/

/***************************************/
/***   Copyright (C) 2009            ***/
/***   BP America, Houston, TX       ***/
/***   Jerry Ehlers, January 2009    ***/
/***************************************/

#include <stdio.h>
#include <string.h>
#include <math.h>

#define LEGAL i=1;j=size;while(j>1) {j /= 2; i *= 2;}; if (i == size)
#define ALIGN(type) (int)(sizeof(struct{char x; type y;}) - sizeof(type))

#define basictype(a, b, c, d) \
   size = sizeof(a); LEGAL { \
   align = ALIGN(a); \
   max_align = (align > max_align) ? align : max_align; \
   printf("#define HOST_" #b "_C   \t1\n"); \
   printf("#define HOST_" #b "_DEF \t" #a "\n"); \
   printf("#define HOST_" #b "_P   \t%d\n", size); \
   printf("#define HOST_" #b "_A   \t%d\n", align); \
   printf("#define HOST_" #b "_DDS \tDDS_" #c "%d%c\n", size, d); \
   printf("typedef HOST_" #b "_DEF \tHOST_" #b "_T;\n\n"); }

#define basictype2(a, b, c, d) \
   size = sizeof(a); LEGAL { \
   align = ALIGN(a); \
   max_align = (align > max_align) ? align : max_align; \
   printf("#define HOST_" #b "_C   \t1\n"); \
   printf("#define HOST_" #b "_DEF \t" #a "\n"); \
   printf("#define HOST_" #b "_P   \t%d\n", size); \
   printf("#define HOST_" #b "_A   \t%d\n", align); \
   printf("#define HOST_" #b "_DDS \tDDS_" #d "%d%c\n", size, cswap); \
   printf("typedef HOST_" #b "_DEF \tHOST_" #b "_T;\n\n"); \
   if (size <= 8 && c[size]==1) { \
      c[size] = -2; \
      printf("#define HOST_" #c "%d_C   \t1\n", size); \
      printf("#define HOST_" #c "%d_DEF \t" #a "\n", size); \
      printf("#define HOST_" #c "%d_P   \t%d\n", size, size); \
      printf("#define HOST_" #c "%d_A   \t%d\n", size, align); \
      printf("#define HOST_" #c "%d_DDS \tHOST_" #b "_DDS\n\n", size); \
   } }
       
#define basictypeCPX(a, b, c)  \
   size = sizeof(struct { a real, imag;}); LEGAL { \
   align = ALIGN(a); \
   printf("#define HOST_" #b "_C \t1\n"); \
   printf("#define HOST_" #b "_DEF \tstruct {" #a " real, imag;}\n"); \
   printf("#define HOST_" #b "_P \t%d\n", size); \
   printf("#define HOST_" #b "_A \t%d\n", align); \
   printf("#define HOST_" #b "_DDS \tDDS_" #c "%d%c\n", size, cswap); \
   printf("typedef HOST_" #b "_DEF \tHOST_" #b "_T;\n\n"); }

typedef union {
   char c; 
   long l;
} malloc_union;


/*! Main Program: Creates most of the chost.h automatically */
int main(int argc, char **argv)
{
   int i, j;
   int size, align, max_align=1, int6=0;
   int INT[9], UINT[9], NONE[9];
   long l;
   char cswap;
   malloc_union uswap;

   /* initialization */
   for(i=0;i<=8;i++) INT[i] = UINT[i] = NONE[i] = -1;
   INT[2] = INT[4] = INT[8] = UINT[8] = 1;

   /* header */
   printf("#ifndef __HOST_H\n#define __HOST_H\n\n");

   printf("/*************************************************************/\n");
   printf("/*                   Copyright (C) 2009                      */\n");
   printf("/*                BP America, Houston, TX                    */\n");
   printf("/*************************************************************/\n");
   printf("/*            --- DO NOD MODIFIED THIS FILE ---              */\n");
   printf("/* The first part of this file is generated by 'makehost'    */\n");
   printf("/* for each platform.  The remainder is taken from of host.h */\n");
   printf("/*                                                           */\n");
   printf("/* Jerry Ehlers - January 2009                               */\n");
   printf("/*************************************************************/\n\n");

   /* Determine if byte swapped (LITTLE ENDIAN) */

   uswap.l = 0;
   uswap.c = (char)91;
   l = uswap.l >> 8*(sizeof(long)-1);
   
   if (uswap.l == 91) {
      cswap = 'X';
      printf("#undef HOST_SWAP\n");
      printf("#define HOST_SWAP \t1\n\n");
   } else if (l == 91) {
      cswap = ' ';
      printf("#undef HOST_SWAP\n\n");
   } else {
      fprintf(stderr,"*** Unknown byte order (l=%lx %lx) ***\n\n",uswap.l,l);
      printf("*** Unknown byte order (l=%lx %lx) ***\n\n",uswap.l,l);
      return -1;
   }

   /*****************************************************/
   /* By default, assume all types are supported by "C" */
   /* If any is not, conditionally turn them off.       */
   /*****************************************************/

   basictype(        void*,   PTR, UNSIGNED, ' ');

   basictype(         char,  CHAR,    ASCII, ' ');
   basictype(  signed char, SCHAR,  INTEGER, ' ');
   basictype(unsigned char, UCHAR, UNSIGNED, ' ');

   basictype2(    short, SHORT, INT, INTEGER);
   basictype2(      int,   INT, INT, INTEGER);
   basictype2(     long,  LONG, INT, INTEGER);
   basictype2(long long, LLONG, INT, INTEGER);

   basictype2(unsigned     short, USHORT, UINT, UNSIGNED);
   basictype2(unsigned          ,   UINT, UINT, UNSIGNED);
   basictype2(unsigned      long,  ULONG, UINT, UNSIGNED);
   basictype2(unsigned long long, ULLONG, UINT, UNSIGNED);

   basictype(      float,   FLOAT, FLOAT, cswap);
   basictype(     double,  DOUBLE, FLOAT, cswap);
   basictype(long double, LDOUBLE, FLOAT, cswap);

   basictypeCPX(      float,     CPX, COMPLEX);
   basictypeCPX(     double,  DBLCPX, COMPLEX);
   basictypeCPX(long double, LDBLCPX, COMPLEX);

   printf("#define HOST_MALLOC_A \t%d\n\n", max_align);

   return 0;
}
